/** 「八股对练」文案（feature 级字典，对齐 features/mail/mail-copy.ts）。 */
export const baguZh = {
	"rail.bagu": "八股对练",
	"bagu.title": "八股对练",
	"bagu.subtitle": "与 AI 面试官相互提问",
	"bagu.apiLabel": "bagu 题库 · localhost:8080",
	"bagu.online": "已连接 bagu",
	"bagu.offline": "bagu 未启动 · 内置题库",
	"bagu.preparing": "正在准备 owl-bagu 目录…",
	"bagu.loading": "题库读取中…",
	"bagu.resync": "重新同步",
	"bagu.finish": "结束复盘",
	"bagu.scope": "题库范围",
	"bagu.all": "全部",
	"bagu.scene": "场景",
	"bagu.scene.campus": "校招一面",
	"bagu.scene.social": "社招二面",
	"bagu.scene.topic": "专题突破",
	"bagu.queue": "题目队列",
	"bagu.queueCount": "{done}/{total}",
	"bagu.queueEmpty": "这个范围暂无题目",
	"bagu.interviewer": "AI 面试官 · 老周",
	"bagu.round": "第 {n} 题",
	"bagu.intro": "你好，我是今天的面试官老周。我们一问一答，你答完我评分、再出下一题；你随时可以切「反问面试官」考我。",
	"bagu.answerMode": "回答",
	"bagu.askMode": "反问面试官",
	"bagu.answerPlaceholder": "按面试的口吻作答，评分看关键词覆盖…",
	"bagu.askPlaceholder": "直接向面试官提问，它会结合题库与模型作答…",
	"bagu.send": "发送",
	"bagu.skip": "跳过",
	"bagu.skipped": "本题已跳过。",
	"bagu.thinking": "老周在想…",
	"bagu.done": "题组刷完了，点「结束复盘」看总结。",
	"bagu.agentOffline": "桥未连接，反问暂不可用。",
	"bagu.evalFailed": "本题评分失败：{message}",
	"bagu.askFailed": "面试官没答上来：{message}",
	"bagu.source.bagu": "bagu 评分",
	"bagu.source.agent": "本地面试官评分",
	"bagu.scoreShort": "{score} 分",
	"bagu.feedbackTag": "评分",
	"bagu.peekShow": "▼ 展开参考答案（评分不看这个，看你的口述）",
	"bagu.peekHide": "▲ 收起参考答案",
	"bagu.retro.title": "本场复盘",
	"bagu.retro.answered": "完成题数",
	"bagu.retro.avg": "平均分",
	"bagu.retro.asks": "反问次数",
	"bagu.retro.weak": "薄弱题目（低于 80 分）",
	"bagu.retro.weakItem": "第 {no} 题（{score} 分）：{title}",
	"bagu.retro.clean": "这场没有明显薄弱点，保持节奏。",
	"bagu.close": "关闭",
	"bagu.linkNote": "题库与学习记录在 bagu（localhost:8080）；「反问」与离线评分由 owl agent 驱动。复盘统计基于本场作答，仅存于内存。",
	"bagu.hintEnterShift": "Enter 发送 · Shift+Enter 换行",
	"bagu.hintEnter": "Enter 发送",
};

export const baguEn: typeof baguZh = {
	"rail.bagu": "Interview drill",
	"bagu.title": "Interview drill",
	"bagu.subtitle": "Quiz each other with an AI interviewer",
	"bagu.apiLabel": "bagu bank · localhost:8080",
	"bagu.online": "bagu connected",
	"bagu.offline": "bagu offline · built-in bank",
	"bagu.preparing": "Preparing the owl-bagu directory…",
	"bagu.loading": "Loading question bank…",
	"bagu.resync": "Resync",
	"bagu.finish": "Wrap up",
	"bagu.scope": "Scope",
	"bagu.all": "All",
	"bagu.scene": "Scenario",
	"bagu.scene.campus": "Campus screen",
	"bagu.scene.social": "Experienced round 2",
	"bagu.scene.topic": "Topic drill",
	"bagu.queue": "Queue",
	"bagu.queueCount": "{done}/{total}",
	"bagu.queueEmpty": "No questions in this scope yet",
	"bagu.interviewer": "AI interviewer · Lao Zhou",
	"bagu.round": "Question {n}",
	"bagu.intro": "Hi, I'm Lao Zhou, today's interviewer. We take turns: you answer, I score and move on. Switch to “Ask the interviewer” anytime to grill me back.",
	"bagu.answerMode": "Answer",
	"bagu.askMode": "Ask the interviewer",
	"bagu.answerPlaceholder": "Answer like in a real interview — scoring checks keyword coverage…",
	"bagu.askPlaceholder": "Ask the interviewer anything — it answers from the bank plus the model…",
	"bagu.send": "Send",
	"bagu.skip": "Skip",
	"bagu.skipped": "Question skipped.",
	"bagu.thinking": "Lao Zhou is thinking…",
	"bagu.done": "Queue finished — wrap up for the recap.",
	"bagu.agentOffline": "Bridge offline — asking is unavailable.",
	"bagu.evalFailed": "Scoring failed: {message}",
	"bagu.askFailed": "The interviewer had no answer: {message}",
	"bagu.source.bagu": "Scored by bagu",
	"bagu.source.agent": "Scored locally",
	"bagu.scoreShort": "{score}",
	"bagu.feedbackTag": "Review",
	"bagu.peekShow": "▼ Show reference answer (scoring only sees what you say)",
	"bagu.peekHide": "▲ Hide reference answer",
	"bagu.retro.title": "Session recap",
	"bagu.retro.answered": "Answered",
	"bagu.retro.avg": "Average",
	"bagu.retro.asks": "Your questions",
	"bagu.retro.weak": "Weak spots (below 80)",
	"bagu.retro.weakItem": "Q{no} ({score}): {title}",
	"bagu.retro.clean": "No weak spots this round. Keep it up.",
	"bagu.close": "Close",
	"bagu.linkNote": "Questions and study records live in bagu (localhost:8080); “Ask” and offline scoring run on the owl agent. Recap stats cover this session and stay in memory.",
	"bagu.hintEnterShift": "Enter to send · Shift+Enter for a new line",
	"bagu.hintEnter": "Enter to send",
};
