/**
 * Re-exports the kernel wire protocol so the UI and bridge share one definition.
 */
export type {
	ApprovalMode,
	DesktopClientRequest,
	DesktopClientRequestWithoutId,
	DesktopServerMessage,
	AuthCancelRequest,
	AuthLoginRequest,
	AuthPromptRespondRequest,
	AuthProvidersRequest,
	ModelInfoMessage,
	ModelsPutModelRequest,
	ModelsPutProviderRequest,
	ModelsRemoveModelRequest,
	ModelsRemoveProviderRequest,
	PermissionRequestMessage,
	ProjectCreateRequest,
	ProjectCreateResult,
	ProviderModelsMessage,
	ServerEventMessage,
	ServerResponseMessage,
	SessionAbortRequest,
	SessionCreateRequest,
	SessionListRequest,
	SessionPromptRequest,
	SessionSetApprovalModeRequest,
	SessionSetModelRequest,
	SessionSetThinkingLevelRequest,
	SessionStatsRequest,
	SessionStatsResult,
	SessionRunningRequest,
	SessionRunningResult,
	SettingsGetRequest,
	SettingsSetRequest,
	SystemPromptPreviewRequest,
	SystemPromptPreviewResult,
	FsEntry,
	FsListing,
	FsReadResult,
	FsReadBinResult,
	FsSearchHit,
	GitStatusResult,
	GitStatusEntry,
	GitLogEntry,
	TermCreateRequest,
	TermCreateResult,
	TermInputRequest,
	TermResizeRequest,
	TermKillRequest,
	TermDataMessage,
	TermExitMessage,
	IabPageInfo,
	IabPagesMessage,
	IabFrameMessage,
	IabServerMessage,
	IabOpenResult,
	IabStateResult,
	IabInputPayload,
} from "../../../../packages/coding-agent/src/modes/desktop/protocol.ts";

import type { PermissionRequestMessage } from "../../../../packages/coding-agent/src/modes/desktop/protocol.ts";

/** Alias used by UI components. */
export type PermissionRequest = PermissionRequestMessage;
