/**
 * Re-exports the kernel wire protocol so the UI and bridge share one definition.
 */
export type {
	MapCategory,
	MapCoordinate,
	MapBounds,
	MapDataSource,
	RealMapPoint,
	RealPlace,
	MapSourceStatus,
	MapResult,
	GeocodeRequest,
	NearbyRequest,
	ReverseRequest,
	MapViewUpdate,
	MapResultsMessage,
} from "../../../../packages/coding-agent/src/core/maps/types.ts";

export type {
	MailClientRequest,
	MailAgentStartRequest,
	MailAgentDraftMessage,
	NewsClientRequest,
	NewsOpenMessage,
	ApprovalMode,
	DesktopApprovalEvent,
	DesktopClientRequest,
	DesktopClientRequestWithoutId,
	DesktopServerMessage,
	AuthCancelRequest,
	AuthLoginRequest,
	AuthPromptRespondRequest,
	AuthProvidersRequest,
	ModelInfoMessage,
	ModelsPutModelRequest,
	ModelsPutProviderRequest,
	ModelsRemoveModelRequest,
	ModelsRemoveProviderRequest,
	PermissionRequestMessage,
	ProjectCreateRequest,
	ProjectCreateResult,
	ProviderModelsMessage,
	QuestionAnswerPayload,
	QuestionOptionPayload,
	QuestionPayload,
	QuestionRequestMessage,
	QuestionResponseRequest,
	CommandsListRequest,
	CommandsListResult,
	SlashCommandEntry,
	SkillCenterEntry,
	SkillCenterRoots,
	SkillCenterTab,
	SkillGroupInfo,
	SkillsGroupsSaveRequest,
	SkillsProjectExtrasRequest,
	SkillsListRequest,
	SkillsListResult,
	SkillsReadRequest,
	SkillsReadResult,
	SkillsSetEnabledRequest,
	SkillsCreateRequest,
	SkillsUpdateRequest,
	SkillsDeleteRequest,
	ServerEventMessage,
	ServerResponseMessage,
	SessionAbortRequest,
	SessionContinueRequest,
	SessionCreateRequest,
	ContextGetRequest,
	ContextGetResult,
	SessionListRequest,
	SessionPromptRequest,
	SessionSetApprovalModeRequest,
	SessionSetPresetRequest,
	PresetListRequest,
	PresetListResult,
	PresetSetDefaultRequest,
	PresetSaveRequest,
	PresetDeleteRequest,
	AgentPresetDefinition,
	SessionSetModelRequest,
	SessionSetThinkingLevelRequest,
	SessionExportLogResult,
	SessionTurn,
	SessionTurnsRequest,
	SessionTurnsResult,
	SessionStatsRequest,
	SessionStatsResult,
	SessionRunningRequest,
	SessionRunningResult,
	SettingsGetRequest,
	SettingsSetRequest,
	SystemPromptPreviewRequest,
	SystemPromptPreviewResult,
	RewindTarget,
	RewindTargetsRequest,
	RewindTargetsResult,
	RewindImpactRequest,
	RewindImpactFile,
	RewindImpactResult,
	RewindExecuteRequest,
	RewindExecuteResult,
	SessionSnapshotPayload,
	MemoryListRequest,
	MemoryListResult,
	OwlMemoryItem,
	MemoryDeleteRequest,
	MemoryClearRequest,
	UsageGetRequest,
	UsageGetResult,
	UsageStatsTotals,
	UsageStatsDay,
	UsageStatsModel,
	UsageStatsProject,
	UsageStatsSession,
	CareerGetRequest,
	CareerGetResult,
	LifeLevel,
	LifeChannel,
	LifeProbeRequest,
	LifeProbeResult,
	CareerAgentUsage,
	CareerAgentTotals,
	CareerSourceStatus,
	CareerBucket,
	OwlImageProvider,
	OwlImageConfigPublic,
	ImageConfigGetRequest,
	ImageConfigGetResult,
	ImageConfigSetRequest,
	ImageConfigSetResult,
	ImageSubLoginRequest,
	ImageSubLoginResult,
	ImageSubLogoutRequest,
	ImageSubLogoutResult,
	ImageModelsListRequest,
	ImageModelsListResult,
	FsEntry,
	FsListing,
	FsReadResult,
	FsReadBinResult,
	FsSearchHit,
	GitStatusResult,
	GitStatusEntry,
	GitLogEntry,
	DiffApprovalStatus,
	DiffApprovalFileSummary,
	DiffApprovalListRequest,
	DiffApprovalListResult,
	DiffApprovalDiffRequest,
	DiffApprovalDiffResult,
	DiffApprovalResolveRequest,
	DiffApprovalResolveResult,
	DiffApprovalClearRequest,
	DiffApprovalClearResult,
	DiffApprovalChangedMessage,
	TermCreateRequest,
	TermCreateResult,
	TermInputRequest,
	TermResizeRequest,
	TermKillRequest,
	TermDataMessage,
	TermExitMessage,
	IabPageInfo,
	IabPagesMessage,
	IabFrameMessage,
	IabServerMessage,
	IabFileChooserMessage,
	IabFileResponseRequest,
	IabOpenResult,
	IabStateResult,
	IabInputPayload,
	MirrorWindowInfo,
	MirrorProjectionGeometry,
	MirrorProjectRequest,
	MirrorInputRequest,
	MirrorServerMessage,
	SidebarOpenMessage,
	ViewerChangedMessage,
	ViewerListRequest,
	ViewerListResult,
	ViewerOpenRequest,
	WorkspaceViewerInfo,
	WorkspaceViewerOpenResult,
} from "../../../../packages/coding-agent/src/modes/desktop/protocol.ts";
// 上下文洞察的 wire 类型本体在 core/context-insight（内核 protocol 也只是转引）
export type { ContextEventRow, ContextRequestRow, ContextToolRef } from "../../../../packages/coding-agent/src/core/context-insight.ts";
export type {
	ScheduleRepeat,
	ScheduleMissedPolicy,
	ScheduleTask,
	ScheduleRun,
	ScheduleListResult,
	ScheduleCreateResult,
	ScheduleUpdateResult,
	ScheduleRunResult,
	ScheduleHistoryResult,
} from "../../../../packages/coding-agent/src/modes/desktop/protocol.ts";
export type * from "../../../../packages/coding-agent/src/core/news/types.ts";
export type * from "../../../../packages/coding-agent/src/core/mail/types.ts";
export type * from "../../../../packages/coding-agent/src/core/evaluation/types.ts";
export type * from "../../../../packages/coding-agent/src/core/research/types.ts";

import type { PermissionRequestMessage, QuestionRequestMessage } from "../../../../packages/coding-agent/src/modes/desktop/protocol.ts";

/** Alias used by UI components. */
export type PermissionRequest = PermissionRequestMessage;
/** Alias used by UI components. */
export type QuestionRequest = QuestionRequestMessage;
