export const mailZh = {
	"rail.mail": "邮箱",
	"mail.showSidebar": "显示邮箱导航",
	"mail.hideSidebar": "隐藏邮箱导航",
	"mail.title": "邮箱",
	"mail.local": "本地",
	"mail.offline": "本地服务未连接",
	"mail.allAccounts": "所有收件箱",
	"mail.accountsCount": "{n} 个 Gmail 账号",
	"mail.accountPicker": "选择邮箱账号",
	"mail.manageAccounts": "管理账号",
	"mail.addAccount": "添加 Gmail 账号",
	"mail.connected": "已连接",
	"mail.expired": "需要重新连接",
	"mail.disconnected": "已断开",
	"mail.readOnly": "仅读取",
	"mail.canSend": "读取与发送",
	"mail.reconnect": "重新连接",
	"mail.disconnect": "断开",
	"mail.disconnectHint": "断开 {email} 后，OWL 将移除本机连接。其他账号可继续使用。已编辑的页面草稿会保留。",
	"mail.rename": "保存名称",
	"mail.accountLabel": "账号名称",
	"mail.folders": "邮箱文件夹",
	"mail.folder.inbox": "收件箱",
	"mail.folder.unread": "未读",
	"mail.folder.starred": "星标",
	"mail.folder.sent": "已发送",
	"mail.folder.drafts": "草稿",
	"mail.accountScope": "当前账号范围",
	"mail.agentCapability": "让 Agent 帮你处理邮件",
	"mail.agentCapabilityHint": "阅读、总结、提取待办、起草回复；发送前由你查看完整内容并确认。",
	"mail.refresh": "刷新邮箱",
	"mail.openAgent": "邮箱助手",
	"mail.closeAgent": "关闭邮箱助手",
	"mail.viewList": "邮件列表",
	"mail.viewReader": "阅读邮件",
	"mail.viewAgent": "Agent 助手",
	"mail.loadedCount": "已加载 {n} 个会话",
	"mail.search": "搜索发件人、主题或邮件内容",
	"mail.searchHint": "支持 Gmail 搜索条件，例如 from:、has:attachment",
	"mail.searchSubmit": "搜索邮件",
	"mail.loading": "正在读取邮件…",
	"mail.loadMore": "加载更多",
	"mail.noMail": "没有找到邮件",
	"mail.noMailHint": "试试其他文件夹或搜索条件。",
	"mail.noAvailableAccount": "当前范围没有可读取的账号，请重新连接。",
	"mail.partialFailure": "以下账号未能读取；已成功读取的邮件仍可查看。",
	"mail.retry": "重试",
	"mail.selectThread": "选择邮件：{subject}",
	"mail.selectedCount": "已选择 {n} 个会话",
	"mail.clearSelection": "清空选择",
	"mail.discussSelection": "交给 Agent",
	"mail.attachmentsCount": "{n} 个附件",
	"mail.messagesCount": "{n} 封邮件",
	"mail.unread": "未读邮件",
	"mail.noSubject": "无主题",
	"mail.chooseMail": "选择一封邮件",
	"mail.chooseMailHint": "查看原文，或让 Agent 帮你总结、提取待办和起草回复。",
	"mail.original": "邮件原文",
	"mail.from": "发件人",
	"mail.to": "收件人",
	"mail.cc": "抄送",
	"mail.bcc": "密送",
	"mail.subject": "主题",
	"mail.body": "邮件正文",
	"mail.sourceAccount": "所属账号",
	"mail.attachmentsMetadata": "附件信息",
	"mail.attachmentsHint": "当前仅展示附件名称和大小，Agent 尚未读取附件内容。",
	"mail.summarize": "总结邮件",
	"mail.tasks": "提取待办",
	"mail.reply": "起草回复",
	"mail.summarizeInbox": "总结当前邮箱",
	"mail.promptSummary":
		"请阅读本次范围内的邮件，按邮件来源总结重点、需要我处理的事项和关键日期。请引用具体账号和邮件主题。",
	"mail.promptMailboxSummary":
		"请在本次账号范围内，搜索符合 Gmail 查询条件「{query}」的邮件，按邮件来源总结重点、需要我处理的事项和关键日期。说明实际查看的邮件数量和时间范围，并引用账号和邮件主题。",
	"mail.promptTasks": "请从本次范围内的邮件提取待办，列出负责人、截止日期和原文依据。缺少信息时明确说明，不要猜测。",
	"mail.promptReply":
		"请阅读当前邮件会话，使用邮箱回复草稿工具为最后一封需要回复的来信起草回复。发件账号必须是原邮件所属账号。未确认的信息请保留为待确认事项，先生成草稿供我编辑。",
	"mail.agentIntro": "从邮件开始对话",
	"mail.agentIntroHint": "选择邮件后直接提问，也可以对当前邮箱范围进行总结。每次对话会固定邮件和账号范围。",
	"mail.agentPlaceholder": "询问邮件内容，或描述你想回复什么…",
	"mail.ask": "发送给 Agent",
	"mail.stop": "停止生成",
	"mail.agentThinking": "正在处理邮件…",
	"mail.agentContext": "本次 Agent 上下文",
	"mail.contextThreads": "{threads} 个会话 · {accounts} 个账号",
	"mail.contextAccounts": "{accounts} 个账号 · 邮箱范围",
	"mail.contextFixed": "阅读其他邮件不会改变本次对话范围。",
	"mail.useCurrentMail": "使用当前邮件开始新对话",
	"mail.conversations": "邮箱对话",
	"mail.conversation": "对话 {n}",
	"mail.source": "查看来源邮件",
	"mail.readSourcesCount": "已读取 {n} 个会话",
	"mail.excludedAccounts": "以下账号未纳入本次对话：{accounts}",
	"mail.agentFailed": "邮箱助手暂时无法完成请求",
	"mail.draft": "回复草稿",
	"mail.newDraft": "Agent 已提供新草稿，当前编辑内容已保留。",
	"mail.adoptDraft": "采用新草稿",
	"mail.draftAlreadySent": "这份草稿已发送。修改内容后可以准备新的邮件。",
	"mail.draftSenderFixed": "发件账号已绑定原邮件；切换账号不会改变发件人。",
	"mail.saveDraft": "保存到 Gmail 草稿",
	"mail.savedDraft": "草稿已保存到 {email}",
	"mail.previewSend": "查看发送预览",
	"mail.saving": "正在保存…",
	"mail.preparing": "正在准备预览…",
	"mail.enableSend": "开启草稿保存与发送",
	"mail.permissionHint": "{email} 当前只有读取权限。编辑草稿可以继续；保存到 Gmail 或发送需要为这个账号补充授权。",
	"mail.draftRetained": "页面草稿已保留，你可以在重新连接后继续。",
	"mail.sendReview": "确认发送邮件",
	"mail.sendReviewHint": "请检查发件账号、所有收件人、主题和完整正文。确认后将发送这封邮件。",
	"mail.confirmSend": "确认发送",
	"mail.sending": "正在发送…",
	"mail.sent": "邮件已通过 {email} 发送",
	"mail.sendUnknown": "暂时无法确认发送结果。请先检查该账号的 Gmail 已发送文件夹，再决定是否重新发送。",
	"mail.confirmExpired": "发送预览已过期，请关闭并重新生成预览。",
	"mail.close": "关闭",
	"mail.cancel": "取消",
	"mail.done": "完成",
	"mail.busy": "正在处理…",
	"mail.error": "请求失败，请重试。",
	"mail.onboardTitle": "把你的邮箱带进 OWL",
	"mail.onboardHint": "连接一个或多个 Gmail 账号，在同一个工作区阅读邮件，并和 Agent 一起处理。",
	"mail.connectGoogle": "通过 Google 连接",
	"mail.onboardPermission": "首先只申请读取权限。需要保存草稿或发送时，再为相应账号授权。",
	"mail.onboardRead": "集中阅读",
	"mail.onboardReadHint": "统一收件箱或单账号查看，每封邮件保留账号来源。",
	"mail.onboardAgent": "与 Agent 对话",
	"mail.onboardAgentHint": "总结、提取待办、拟回复，保留具体邮件来源。",
	"mail.onboardConfirm": "你决定何时发送",
	"mail.onboardConfirmHint": "草稿可编辑，发送前展示完整预览。",
	"mail.connectTitle": "连接 Gmail 账号",
	"mail.configureStep": "准备 Google 授权",
	"mail.authorizeStep": "登录并连接",
	"mail.configureHint":
		"首次连接需要在 Google Cloud 中启用 Gmail API，创建“桌面应用”类型的 OAuth 客户端，并下载客户端 JSON 文件。测试应用需要将自己的邮箱添加为测试用户。",
	"mail.googleConsole": "打开 Google Cloud 配置",
	"mail.chooseClient": "选择客户端 JSON 文件",
	"mail.clientConfigured": "Google 授权配置已就绪",
	"mail.replaceClient": "更换配置文件",
	"mail.clientPrivacy": "授权凭据仅保存在此设备上，不会加入聊天或提交到项目。",
	"mail.authReadHint": "在浏览器中选择要连接的 Google 账号。可以继续添加其他账号，各账号的授权分别管理。",
	"mail.authSendHint": "将为 {email} 申请保存草稿与发送权限。完成授权后，仍需回到这里逐封确认发送。",
	"mail.authWaiting": "等待 Google 授权完成…",
	"mail.authWaitingHint": "请在浏览器中完成登录并允许访问。此窗口会自动检查连接结果。",
	"mail.openAuth": "重新打开授权页面",
	"mail.authFailed": "连接未完成，草稿和其他账号的连接已保留。",
	"mail.authExpired": "本次授权已过期，请重新连接。",
	"mail.accountAdded": "已连接 {email}",
	"mail.invalidFile": "请选择有效的 Google 客户端 JSON 文件。",
	"mail.confirmDisconnect": "确认断开账号",
} as const;

export const mailEn: { [K in keyof typeof mailZh]: string } = {
	"rail.mail": "Mail",
	"mail.showSidebar": "Show mailbox navigation",
	"mail.hideSidebar": "Hide mailbox navigation",
	"mail.title": "Mail",
	"mail.local": "Local",
	"mail.offline": "Local service disconnected",
	"mail.allAccounts": "All inboxes",
	"mail.accountsCount": "{n} Gmail accounts",
	"mail.accountPicker": "Choose mail account",
	"mail.manageAccounts": "Manage accounts",
	"mail.addAccount": "Add Gmail account",
	"mail.connected": "Connected",
	"mail.expired": "Reconnect required",
	"mail.disconnected": "Disconnected",
	"mail.readOnly": "Read only",
	"mail.canSend": "Read and send",
	"mail.reconnect": "Reconnect",
	"mail.disconnect": "Disconnect",
	"mail.disconnectHint":
		"Disconnecting {email} removes its local connection. Other accounts can continue working. Edited drafts remain on this page.",
	"mail.rename": "Save name",
	"mail.accountLabel": "Account name",
	"mail.folders": "Mail folders",
	"mail.folder.inbox": "Inbox",
	"mail.folder.unread": "Unread",
	"mail.folder.starred": "Starred",
	"mail.folder.sent": "Sent",
	"mail.folder.drafts": "Drafts",
	"mail.accountScope": "Current account scope",
	"mail.agentCapability": "Work through mail with your Agent",
	"mail.agentCapabilityHint":
		"Read, summarize, extract tasks and draft replies. Review the complete message before confirming a send.",
	"mail.refresh": "Refresh mail",
	"mail.openAgent": "Mail assistant",
	"mail.closeAgent": "Close mail assistant",
	"mail.viewList": "Mail list",
	"mail.viewReader": "Read mail",
	"mail.viewAgent": "Agent assistant",
	"mail.loadedCount": "{n} conversations loaded",
	"mail.search": "Search sender, subject or mail content",
	"mail.searchHint": "Supports Gmail search, such as from: and has:attachment",
	"mail.searchSubmit": "Search mail",
	"mail.loading": "Reading mail…",
	"mail.loadMore": "Load more",
	"mail.noMail": "No mail found",
	"mail.noMailHint": "Try another folder or search.",
	"mail.noAvailableAccount": "No readable accounts in this scope. Reconnect an account to continue.",
	"mail.partialFailure": "These accounts could not be read. Mail from other accounts remains available.",
	"mail.retry": "Retry",
	"mail.selectThread": "Select mail: {subject}",
	"mail.selectedCount": "{n} conversations selected",
	"mail.clearSelection": "Clear selection",
	"mail.discussSelection": "Ask Agent",
	"mail.attachmentsCount": "{n} attachments",
	"mail.messagesCount": "{n} messages",
	"mail.unread": "Unread mail",
	"mail.noSubject": "No subject",
	"mail.chooseMail": "Choose a message",
	"mail.chooseMailHint": "Read the original or ask your Agent for a summary, tasks or reply draft.",
	"mail.original": "Original message",
	"mail.from": "From",
	"mail.to": "To",
	"mail.cc": "Cc",
	"mail.bcc": "Bcc",
	"mail.subject": "Subject",
	"mail.body": "Message body",
	"mail.sourceAccount": "Source account",
	"mail.attachmentsMetadata": "Attachment details",
	"mail.attachmentsHint": "Only attachment names and sizes are shown. The Agent has not read their contents.",
	"mail.summarize": "Summarize",
	"mail.tasks": "Extract tasks",
	"mail.reply": "Draft reply",
	"mail.summarizeInbox": "Summarize this mailbox",
	"mail.promptSummary":
		"Read the mail in this scope and summarize key points, actions I need to take and important dates. Cite the specific account and message subject.",
	"mail.promptMailboxSummary":
		"Within this account scope, search for mail matching the Gmail query ‘{query}’. Summarize key points, actions I need to take and important dates. State the actual number of messages and date range reviewed, and cite the account and subject.",
	"mail.promptTasks":
		"Extract tasks from the mail in this scope, including owner, due date and original evidence. Clearly identify missing information instead of guessing.",
	"mail.promptReply":
		"Read the selected conversation and use the mail reply draft tool to draft a response to the last incoming message needing a reply. Use the original message's account as the sender. Leave unconfirmed information as questions and create a draft for me to edit.",
	"mail.agentIntro": "Start a conversation from your mail",
	"mail.agentIntroHint":
		"Select mail and ask a question, or summarize the current mailbox. Each conversation keeps a fixed mail and account scope.",
	"mail.agentPlaceholder": "Ask about this mail or describe your reply…",
	"mail.ask": "Ask Agent",
	"mail.stop": "Stop generation",
	"mail.agentThinking": "Working through your mail…",
	"mail.agentContext": "Agent context for this conversation",
	"mail.contextThreads": "{threads} conversations · {accounts} accounts",
	"mail.contextAccounts": "{accounts} accounts · mailbox scope",
	"mail.contextFixed": "Reading other mail does not change this conversation's scope.",
	"mail.useCurrentMail": "Start a new conversation with this mail",
	"mail.conversations": "Mail conversations",
	"mail.conversation": "Conversation {n}",
	"mail.source": "View source mail",
	"mail.readSourcesCount": "{n} conversations read",
	"mail.excludedAccounts": "Accounts excluded from this conversation: {accounts}",
	"mail.agentFailed": "The mail assistant could not complete the request",
	"mail.draft": "Reply draft",
	"mail.newDraft": "The Agent provided a new draft. Your current edits have been preserved.",
	"mail.adoptDraft": "Use new draft",
	"mail.draftAlreadySent": "This draft has been sent. Edit its content to prepare a new message.",
	"mail.draftSenderFixed": "The sender is bound to the original mail. Switching accounts will not change it.",
	"mail.saveDraft": "Save to Gmail drafts",
	"mail.savedDraft": "Draft saved to {email}",
	"mail.previewSend": "Preview send",
	"mail.saving": "Saving…",
	"mail.preparing": "Preparing preview…",
	"mail.enableSend": "Enable saving drafts and sending",
	"mail.permissionHint":
		"{email} currently has read-only access. You can edit the draft; saving to Gmail or sending requires additional authorization for this account.",
	"mail.draftRetained": "Your draft remains on this page so you can continue after reconnecting.",
	"mail.sendReview": "Confirm sending this message",
	"mail.sendReviewHint":
		"Check the sending account, every recipient, subject and complete body. Confirming sends this message.",
	"mail.confirmSend": "Confirm send",
	"mail.sending": "Sending…",
	"mail.sent": "Mail sent through {email}",
	"mail.sendUnknown":
		"The send result could not be confirmed. Check this account's Gmail Sent folder before deciding to send again.",
	"mail.confirmExpired": "This send preview has expired. Close it and create a new preview.",
	"mail.close": "Close",
	"mail.cancel": "Cancel",
	"mail.done": "Done",
	"mail.busy": "Working…",
	"mail.error": "Request failed. Please try again.",
	"mail.onboardTitle": "Bring your mail into OWL",
	"mail.onboardHint":
		"Connect one or more Gmail accounts, read mail in one workspace and work through it with your Agent.",
	"mail.connectGoogle": "Connect with Google",
	"mail.onboardPermission":
		"Start with read-only access. Authorize the individual account when you need to save a draft or send.",
	"mail.onboardRead": "Read in one place",
	"mail.onboardReadHint": "View all inboxes or one account, with the source account shown on every message.",
	"mail.onboardAgent": "Talk with your Agent",
	"mail.onboardAgentHint": "Summarize, extract tasks and draft replies with traceable mail sources.",
	"mail.onboardConfirm": "You decide when to send",
	"mail.onboardConfirmHint": "Edit the draft and review the complete preview before sending.",
	"mail.connectTitle": "Connect a Gmail account",
	"mail.configureStep": "Prepare Google authorization",
	"mail.authorizeStep": "Sign in and connect",
	"mail.configureHint":
		"For the first connection, enable Gmail API in Google Cloud, create a Desktop app OAuth client and download its client JSON. For a testing app, add your email as a test user.",
	"mail.googleConsole": "Open Google Cloud configuration",
	"mail.chooseClient": "Choose client JSON file",
	"mail.clientConfigured": "Google authorization is configured",
	"mail.replaceClient": "Replace configuration file",
	"mail.clientPrivacy":
		"Authorization credentials stay on this device. They are not added to chat or committed to the project.",
	"mail.authReadHint":
		"Choose the Google account in your browser. You can add more accounts later; permissions are managed separately.",
	"mail.authSendHint":
		"Authorize saving drafts and sending for {email}. After authorization, return here to review and confirm each message.",
	"mail.authWaiting": "Waiting for Google authorization…",
	"mail.authWaitingHint": "Sign in and allow access in the browser. This window checks the connection automatically.",
	"mail.openAuth": "Reopen authorization page",
	"mail.authFailed": "Connection was not completed. Drafts and connections to other accounts remain available.",
	"mail.authExpired": "This authorization has expired. Please connect again.",
	"mail.accountAdded": "Connected {email}",
	"mail.invalidFile": "Choose a valid Google client JSON file.",
	"mail.confirmDisconnect": "Confirm account disconnect",
};
