const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const dir=__dirname;
const root=path.resolve(dir,'../..');
const template=fs.readFileSync('C:/Users/李现/.codex/skills/frontend-design/assets/preview-template.html','utf8').replace(/\r\n/g,'\n');
const lines=template.split('\n');
// Lift only review controls, preview frame and feedback machinery. Omit sample styles/content/tokens.
const allCss=template.match(/<style>([^]*?)<\/style>/)[1];
const scaffoldCss=allCss.slice(allCss.indexOf('  * { box-sizing'),allCss.indexOf('  .preview .label'))+'\n'+allCss.slice(allCss.indexOf('  /* Direct edits */'));
let scaffoldJs=template.slice(template.indexOf('const decisions = {}'),template.lastIndexOf('</script>'));
scaffoldJs=scaffoldJs.replace("const ts = new Date().toISOString().slice(0, 19).replace('T', ' ');","const ts = new Date().toLocaleString('sv-SE',{timeZone:'Asia/Taipei'});");
scaffoldJs=scaffoldJs.replace("lines.push('When applying these changes:');","lines.push('先继续迭代原型。只有用户明确批准实施后，才修改应用源码；映射见同目录 COVERAGE.md。');");
scaffoldJs=scaffoldJs.replace("under `:root` (typography/radius/spacing), `.theme-light`, and `.theme-dark` blocks", "using the existing `@theme` and `html[data-owl-theme=\"light\"]` blocks");
scaffoldJs=scaffoldJs.replace("**Verify** — build / lint / preview as appropriate for the project. Optionally regenerate the preview HTML to confirm the new state.","**Verify** — follow AGENTS.md, inspect the frontend in both themes and run the authorized checks. Do not run a build without user authorization.");
scaffoldJs=scaffoldJs.replace('  return edits;\n}',`  for(const [key,edit] of recordedEdits){ if(!seen.has(key))edits.push(edit); }\n  return edits;\n}`);
scaffoldJs=scaffoldJs.replace('  resetDirectEdits();','  resetDirectEdits();\n  recordedEdits.clear(); editedValues.clear();');
const translations=[['Exit Comment Mode','退出标注'],['Comment Mode','标注意见'],['Hide Markers','隐藏标记'],['Show Markers','显示标记'],['Note is empty','请填写意见'],['Copied to clipboard','意见已复制，可粘贴回聊天'],['Copied (fallback)','意见已复制'],['Nothing to export — change a decision, edit text, or add a comment first','先调整样式、编辑文案或添加意见，再导出。'],["showToast('Reset')","showToast('已重置设计意见')"],['Show controls panel','展开设计控制'],['Collapse controls panel','收起设计控制'],["collapsed ? 'Show' : 'Collapse'","collapsed ? '展开' : '收起'"],['This element','仅此元素'],['All matching','同类组件'],['All like this','同组元素'],['Global','全局'],['No comments yet.','暂无意见。']];
for(const [a,b] of translations)scaffoldJs=scaffoldJs.replaceAll(a,b);
const metadata=`const PREVIEW_META = {source:'.frontend-design/owl-redesign/2026-10-03-owl-redesign.html',topic:'owl-complete-redesign',targetFile:'apps/desktop/src/index.css'};
const recordedEdits = new Map();
const TOKENS = {
  owlIdentity:[{key:'--color-owl-accent',intent:'OWL 绿色 · 主要操作与状态',kind:'color',options:[{id:'原色',light:'#2f9e5a',dark:'#2f9e5a',note:'保留现有品牌色 (default)'},{id:'沉稳',light:'#287a46',dark:'#49b970',note:'浅色更稳，深色稍亮'}]}],
  owlCanvas:[{key:'--color-owl-bg',intent:'主画布 · 暖纸或中性灰',kind:'color',defaultId:'石墨',options:[{id:'石墨',light:'#fafbf9',dark:'#202321',note:'本轮设计 · 减少暖灰杂色 (default)'},{id:'现有',light:'#faf9f5',dark:'#262624',note:'项目当前配色'},{id:'纸感',light:'#f8f7f2',dark:'#242623',note:'更温暖的阅读体验'}]},{key:'--color-owl-panel',intent:'输入框、工作台与表单表面',kind:'color',options:[{id:'清晰',light:'#ffffff',dark:'#282d29',note:'层次清楚 (default)'},{id:'柔和',light:'#f7f9f6',dark:'#252a26',note:'减少表面反差'}]}],
  owlNavigation:[{key:'--color-owl-sidebar-bg',intent:'会话列表与设置导航背景',kind:'color',options:[{id:'克制',light:'#f1f3ef',dark:'#191d1a',note:'本轮设计 (default)'},{id:'现有',light:'#f3f3f3',dark:'#1c1c1c',note:'现有中性导航'}]},{key:'--color-owl-sidebar-border',intent:'导航与面板分隔线',kind:'color',options:[{id:'细线',light:'#e0e5df',dark:'#343c35',note:'柔和的层级分隔 (default)'},{id:'清楚',light:'#d2dad1',dark:'#485248',note:'较强对比'}]}],
  owlReading:[{key:'--font-serif',intent:'AI 回复 · 保留衬线或统一无衬线',kind:'dropdown',options:[{id:'现有',value:'Georgia, "Microsoft YaHei", "PingFang SC", serif',note:'现有回答字体 (default)'},{id:'统一',value:'"Segoe UI", "Microsoft YaHei", "PingFang SC", system-ui, sans-serif',note:'与工具、设置统一'}]}]
};
const SECTION_ORDER = [['品牌识别','owlIdentity'],['工作画布','owlCanvas'],['导航层次','owlNavigation'],['阅读体验','owlReading']];`;
const shellJs=fs.readFileSync(path.join(dir,'shell.js'),'utf8').replace("'__OWL_SVG__'",JSON.stringify(fs.readFileSync(path.join(root,'apps/desktop/public/owl.svg'),'utf8').replace(/<!--[^]*?-->/g,'')));
const feedbackMarkup=lines.slice(1092,1154).join('\n').replaceAll('↑ Parent','↑ 父级').replaceAll('↓ Child','↓ 子级').replaceAll('What change do you want here?','这里希望如何调整？').replaceAll('Scope','范围').replaceAll('>Save<','>保存意见<').replaceAll('>Cancel<','>取消<').replaceAll('>Delete<','>删除<').replaceAll('>Copy<','>复制<').replaceAll('>Close<','>关闭<').replaceAll('>Export<','>导出设计意见<').replaceAll('Comments <span','设计意见 <span').replace('No comments yet. Click <strong>Comment Mode</strong> in the header, then click any element in the preview to annotate.','点击顶部“标注意见”，然后点击原型中的元素，即可添加修改建议。');
const document=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OWL · 完整界面重设计 / 第 1 轮</title><style>${scaffoldCss}\n${fs.readFileSync(path.join(dir,'shell.css'),'utf8')}</style></head><body>
<div class="app"><header class="app-header"><div><h1>OWL <span style="color:#a1aaa2;font-weight:400;margin:0 7px">/</span> 完整界面重设计 <span style="font-size:10px;color:#2f9e5a;border:1px solid #2f9e5a30;border-radius:4px;padding:2px 6px;margin-left:9px;vertical-align:middle">第 1 轮 · 待确认</span></h1><div class="subtitle">保留 OWL 绿 · 专业石墨灰 · 2026.10.03　所有操作均为原型演示，确认后再实施。</div></div><div class="actions"><button class="btn" id="comment-mode-btn"><span id="comment-mode-label">标注意见</span></button><button class="btn" id="markers-btn"><span id="markers-label">显示标记</span></button><button class="btn" id="comment-list-btn">意见 <span id="comment-count">(0)</span></button><button class="btn" id="reset-btn">重置意见</button><button class="btn primary" id="export-btn">导出给 Codex</button></div></header>
<div class="main-layout"><aside class="controls" id="controls-rail"><div class="controls-toggle-row"><button class="toggle-btn" id="toggle-controls-btn" aria-pressed="false"><span id="toggle-controls-icon">◀</span><span id="toggle-controls-label">收起</span></button></div><div id="screen-catalog" class="catalog" style="padding:0 12px;max-height:46vh;overflow:auto"></div><div class="controls-body" id="controls-body"><div class="help-banner">在上方切换页面。点击右侧主题箭头可放大。文字可直接编辑；开启“标注意见”可点选任意元素，最后导出意见。</div></div></aside>
<section class="preview-pair" id="preview-pair"><div class="review-tabs"><span style="font-size:11px;color:#8a978d;margin-right:5px">查看方式</span><button data-review-theme="split" class="active">浅色 / 深色对照</button><button data-review-theme="light-expanded">浅色放大</button><button data-review-theme="dark-expanded">深色放大</button><span style="margin-left:auto;font-size:10px;color:#8a978d;padding-right:8px">设计画布 1280 × 800</span></div><div class="preview-grid"><div class="preview theme-light" id="preview-light" data-theme="light"><button class="pane-toggle-btn" data-pane="light" aria-label="放大浅色效果" title="放大浅色效果">▶</button><div class="theme-cap"><span class="cap-dot"></span> LIGHT / 浅色</div><div class="canvas-frame" data-owl-mount></div><div class="screen-note">保留现有页面能力，重新整理层级与视觉。点击导航、按钮或输入框体验。</div></div><div class="preview theme-dark" id="preview-dark" data-theme="dark"><button class="pane-toggle-btn" data-pane="dark" aria-label="放大深色效果" title="放大深色效果">◀</button><div class="theme-cap"><span class="cap-dot"></span> DARK / 深色</div><div class="canvas-frame" data-owl-mount></div><div class="screen-note">与浅色使用相同的结构、内容与操作；绿色仅承担主要行动与状态。</div></div></div></section></div></div>
${feedbackMarkup}
<script>${metadata}\n${scaffoldJs}</script>
<script>${fs.readFileSync(path.join(dir,'workspace-views.js'),'utf8')}\n${fs.readFileSync(path.join(dir,'settings-views.js'),'utf8')}\n${fs.readFileSync(path.join(dir,'dialog-views.js'),'utf8')}\n${shellJs}</script>
</body></html>`;
fs.writeFileSync(path.join(dir,'2026-10-03-owl-redesign.html'),document);
// Protect the pre-existing dirty app state by fingerprinting source files; only prototype outputs are written.
function files(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(x=>x.isDirectory()?files(path.join(dir,x.name)):[path.join(dir,x.name)]);}
if(!fs.existsSync(path.join(dir,'source-baseline.json'))){const hashes=Object.fromEntries(files(path.join(root,'apps/desktop/src')).map(f=>[path.relative(root,f),crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')]));fs.writeFileSync(path.join(dir,'source-baseline.json'),JSON.stringify(hashes,null,2));}
fs.writeFileSync(path.join(dir,'inline-syntax-check.js'),[metadata,scaffoldJs,fs.readFileSync(path.join(dir,'workspace-views.js'),'utf8'),fs.readFileSync(path.join(dir,'settings-views.js'),'utf8'),fs.readFileSync(path.join(dir,'dialog-views.js'),'utf8'),shellJs].join('\n'));
console.log(JSON.stringify({output:path.join(dir,'2026-10-03-owl-redesign.html'),bytes:Buffer.byteLength(document),externalResources:/<script\s+src=|<link[^>]+rel=["']stylesheet|@import|url\(["']?https?:/.test(document)},null,2));
