/* OWL review prototype. This file contains demo UI only and never connects to the application bridge. */
(function () {
  const footer = (label, action, danger = false, hint = '') => `<div style="display:flex;align-items:center;justify-content:space-between;gap:16px;margin-top:24px;padding-top:18px;border-top:1px solid var(--border)"><span class="small muted">${hint}</span><div style="display:flex;gap:8px">${button('取消','close-modal','ghost')}${button(label,action,danger?'danger':'primary')}</div></div>`;
  const menuItem = (id, glyph, title, action, description = '', value = '', selected = false, danger = false) => `<button type="button" class="menu-item" data-fd-id="${id}" data-action="${action}"${value ? ` data-value="${value}"` : ''} style="display:flex;align-items:center;gap:12px;width:100%;padding:13px 14px;text-align:left;${selected ? 'background:var(--accent-soft);' : ''}${danger ? 'color:#d14d4d;' : ''}">${icon(glyph,18)}<span style="flex:1;min-width:0"><span data-fd-editable="true" style="display:block;font-weight:550">${title}</span>${description ? `<span class="small muted" data-fd-editable="true" style="display:block;margin-top:4px;line-height:1.5">${description}</span>` : ''}</span>${selected ? `<span style="color:var(--accent,#2f9e5a)">${icon('check',16)}</span>` : ''}</button>`;
  const modelItem = (id, title, context, reasoning, selected = false) => `<button type="button" class="menu-item" data-fd-id="dialog-model-${id}" data-action="choose-model" data-value="${id}" style="display:flex;align-items:center;gap:12px;width:100%;padding:13px 14px;text-align:left;${selected ? 'background:var(--accent-soft);' : ''}"><span style="width:32px;height:32px;display:grid;place-items:center;border:1px solid var(--border);border-radius:9px">${icon('cpu',17)}</span><span style="flex:1"><strong data-fd-editable="true" style="font-size:13px;font-weight:550">${title}</strong><span class="small muted" style="display:block;margin-top:4px">${context} tokens 上下文${reasoning ? ' · 支持思考' : ''}</span></span>${selected ? `<span style="color:var(--accent,#2f9e5a)">${icon('check',18)}</span>` : ''}</button>`;
  const option = (id, title, description, selected = false, multi = false, preview = '') => `<div data-fd-id="${id}" style="border:1px solid ${selected ? 'var(--accent,#2f9e5a)' : 'var(--border)'};border-radius:11px;background:${selected ? 'var(--accent-soft)' : 'transparent'}"><label style="display:flex;align-items:flex-start;gap:11px;padding:14px;cursor:pointer"><input name="${multi ? id : 'owl-design-choice'}" type="${multi ? 'checkbox' : 'radio'}" ${selected ? 'checked' : ''} style="margin:3px 0 0;accent-color:#2f9e5a"><span style="flex:1"><strong data-fd-editable="true" style="font-size:13px;font-weight:550">${title}</strong><span class="small muted" data-fd-editable="true" style="display:block;line-height:1.6;margin-top:4px">${description}</span></span>${selected ? tag('已选择','green') : ''}</label>${preview ? `<details style="padding:0 14px 12px 39px"><summary class="small muted" style="cursor:pointer">查看方案预览</summary><div class="notice" style="margin-top:10px;font-size:12px;line-height:1.7">${preview}</div></details>` : ''}</div>`;
  const questionProgress = (current, count = 2) => `<div data-fd-id="dialog-question-progress" style="display:flex;align-items:center;gap:12px;margin-bottom:22px"><span class="tag green">第 ${current} / ${count} 题</span><div style="display:flex;flex:1;gap:6px">${Array.from({length:count},(_,i)=>`<span style="height:4px;flex:1;border-radius:4px;background:${i<current?'var(--accent,#2f9e5a)':'var(--border)'}"></span>`).join('')}</div><span class="small muted">${current===1?'单选':'可多选'}</span></div>`;
  const questionNotes = () => `<details data-fd-id="dialog-question-notes" style="margin-top:16px"><summary class="small muted" style="cursor:pointer">＋ 添加备注</summary><textarea class="textarea" aria-label="这道题的备注" placeholder="补充说明，将与本题答案一起发送" rows="2" style="width:100%;margin-top:10px"></textarea></details>`;

  window.OWL_DIALOGS = {
    project: {
      title: '添加项目',
      html: () => `<div class="form-stack" data-fd-id="dialog-project-content"><div class="notice" style="display:flex;align-items:center;gap:12px">${icon('folder',22)}<div><strong data-fd-editable="true" style="display:block;font-weight:550">从你的项目目录开始</strong><p class="small muted" data-fd-editable="true" style="margin:4px 0 0;line-height:1.6">选择已有目录，或输入新目录路径。OWL 会自动创建不存在的目录。</p></div></div>${field('项目目录','请输入完整路径',`<div style="display:flex;gap:8px"><input class="input" data-fd-id="dialog-project-path" style="flex:1;min-width:0;font-family:var(--mono,monospace)" value="D:\\work\\new-project" placeholder="D:\\work\\new-project" aria-label="项目目录">${button('浏览…','project-browse','ghost')}</div>`)}<p class="small muted" data-fd-editable="true" style="margin:0">添加后会切换到这个项目，并开始新的会话。</p></div>${footer('添加并切换','project-create',false,'Enter 确认 · Esc 取消')}`,
    },
    permission: {
      title: '允许这次工具调用？',
      html: () => `<div class="form-stack" data-fd-id="dialog-permission-content"><div style="display:flex;align-items:center;gap:12px"><span style="width:40px;height:40px;display:grid;place-items:center;border-radius:12px;background:var(--accent-soft);color:var(--accent,#2f9e5a)">${icon('shield',22)}</span><div><strong data-fd-editable="true" style="font-weight:550">OWL 请求运行命令</strong><p class="small muted" style="margin:4px 0 0">当前项目 · owl-mono</p></div>${tag('等待确认')}</div><div class="card" style="padding:0;overflow:hidden"><div style="display:flex;align-items:center;justify-content:space-between;padding:12px 15px;border-bottom:1px solid var(--border)"><span class="small muted">工具</span><code class="small" style="color:var(--accent,#2f9e5a)">bash</code></div><pre class="code" data-fd-id="dialog-permission-command" data-fd-editable="true" style="margin:0;padding:18px;font-size:12px;line-height:1.8;white-space:pre-wrap;background:transparent">npm run check</pre><div class="small muted" style="padding:0 18px 15px">工作目录：D:\\owl\\owl-re-v1\\owl-mono</div></div><p class="small muted" data-fd-editable="true" style="line-height:1.7;margin:0">标准模式下，每次工具调用都会先征求你的同意。</p></div><div style="display:flex;justify-content:flex-end;gap:8px;margin-top:24px;padding-top:18px;border-top:1px solid var(--border)">${button('拒绝','reject','ghost')}${button('允许这次调用','allow','primary')}</div>`,
    },
    question: {
      title: '需要你做一个选择',
      html: () => `<div data-fd-id="dialog-question-content">${questionProgress(1)}<h3 data-fd-editable="true" style="font-size:15px;font-weight:600;margin:0 0 7px">这一轮 OWL 的整体视觉，你更偏向哪种方向？</h3><p class="small muted" data-fd-editable="true" style="margin:0 0 18px;line-height:1.6">你的选择会帮助 OWL 收敛后续方案。</p><div class="form-stack" style="gap:10px">${option('question-neutral','克制专业','清晰留白、石墨灰与 OWL 绿色点缀。',true,false,'使用安静的中性色建立层级，绿色只用于主要操作、选中状态和成功反馈。')}${option('question-focused','深色专注','深石墨背景，降低视觉干扰，突出工作内容。',false,false,'更适合长时间专注工作；主界面仍然保留清晰的内容层级与绿色操作入口。')}<label class="field" style="display:flex;align-items:center;gap:10px;padding:11px 14px;border:1px solid var(--border);border-radius:11px"><span class="small muted">其他</span><input class="input" aria-label="其他视觉方向" placeholder="写下你的想法…" style="border:0;padding:2px;background:transparent;min-width:0;flex:1"></label></div>${questionNotes()}<div style="display:flex;justify-content:space-between;align-items:center;margin-top:23px;padding-top:18px;border-top:1px solid var(--border)">${button('取消','question-cancel','ghost')}<div style="display:flex;gap:10px;align-items:center"><span class="small muted">Ctrl + Enter</span>${button('下一题','question-next','primary')}</div></div></div>`,
    },
    questionFinal: {
      title: '需要你做一个选择',
      html: () => `<div data-fd-id="dialog-question-final">${questionProgress(2)}<h3 data-fd-editable="true" style="font-size:15px;font-weight:600;margin:0 0 7px">哪些界面需要优先打磨？</h3><p class="small muted" data-fd-editable="true" style="margin:0 0 18px;line-height:1.6">可选择多个选项，也可以补充其他重点。</p><div class="form-stack" style="gap:10px">${option('question-chat','对话工作区','会话层级、消息阅读和输入体验。',true,true)}${option('question-settings','设置与模型管理','分类导航、表单布局和配置反馈。',true,true)}${option('question-permission','工具确认与提问','让每次决策的信息更清楚。',false,true)}${field('其他重点','',input('','自由补充…'))}</div>${questionNotes()}<div style="display:flex;justify-content:space-between;align-items:center;margin-top:23px;padding-top:18px;border-top:1px solid var(--border)">${button('取消','question-cancel','ghost')}<div style="display:flex;gap:8px">${button('上一题','question-prev','ghost')}${button('提交回答','question-submit','primary')}</div></div></div>`,
    },
    model: {
      title: '选择模型',
      html: () => `<div data-fd-id="dialog-model-list"><div style="display:flex;align-items:center;gap:9px;margin-bottom:16px">${icon('search',17)}<input class="input" aria-label="搜索模型" placeholder="搜索已添加的模型…" style="flex:1"></div><p class="small muted" data-fd-editable="true" style="margin:0 0 8px">工作模型 · 示例配置</p><div class="menu-list" style="border:1px solid var(--border);border-radius:12px;overflow:hidden">${modelItem('demo/owl-coder','主力编码模型','128,000',true,true)}${modelItem('demo/owl-fast','快速模型','128,000',false)}${modelItem('demo/owl-reasoner','深度推理模型','200,000',true)}</div><p class="small muted" data-fd-editable="true" style="margin:16px 0 0;line-height:1.7">这里展示你在「模型与供应商」中添加的模型。</p><div style="display:flex;justify-content:flex-end;margin-top:17px">${button('管理模型','manage-models','ghost')}</div></div>`,
    },
    mode: {
      title: '工作模式',
      html: () => `<div data-fd-id="dialog-mode-list"><p class="small muted" data-fd-editable="true" style="margin:0 0 16px;line-height:1.7">根据任务调整 OWL 的执行权限。</p><div class="menu-list" style="border:1px solid var(--border);border-radius:12px;overflow:hidden">${menuItem('dialog-mode-plan','compass','计划模式','choose-mode','使用只读工具调研，并给出实施计划。','plan')}${menuItem('dialog-mode-standard','shield','标准模式','choose-mode','每次工具调用前，由你确认是否执行。','confirm',true)}${menuItem('dialog-mode-auto','zap','自动模式','choose-mode','自动执行工具调用，无需逐次确认。','auto')}</div><div class="notice" data-fd-id="dialog-mode-note" style="margin-top:17px;font-size:12px;line-height:1.7">当前使用标准模式。需要执行操作时，OWL 会给出具体内容供你确认。</div></div>`,
    },
    thinking: {
      title: '思考强度',
      html: () => `<div data-fd-id="dialog-thinking"><p class="small muted" data-fd-editable="true" style="margin:0 0 15px;line-height:1.7">可选档位取决于当前模型的能力。</p><div class="menu-list" style="border:1px solid var(--border);border-radius:12px;overflow:hidden">${[['off','关闭'],['minimal','最低'],['low','低'],['medium','中'],['high','高'],['xhigh','超高'],['max','最高']].map(([v,t])=>menuItem('dialog-thinking-'+v,'brain',t,'choose-thinking','',v,v==='high')).join('')}</div></div>`,
    },
    context: {
      title: '上下文与用量',
      html: () => `<div class="form-stack" data-fd-id="dialog-context-content"><div class="card"><div style="display:flex;align-items:flex-end;justify-content:space-between;gap:12px"><div><p class="small muted" style="margin:0 0 8px">当前上下文窗口</p><strong style="font-size:26px;font-weight:600;letter-spacing:-1px">24.8k <span class="muted" style="font-size:15px;font-weight:400;letter-spacing:0">/ 128k</span></strong></div>${tag('19%','green')}</div><div style="height:6px;border-radius:8px;background:var(--border);overflow:hidden;margin-top:17px"><div style="height:100%;width:19%;background:var(--accent,#2f9e5a);border-radius:8px"></div></div></div><div class="card"><p data-fd-editable="true" style="font-size:13px;font-weight:550;margin:0 0 15px">本次会话累计</p><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:15px"><div><p class="small muted" style="margin:0 0 7px">输入</p><strong style="font-size:16px;font-weight:550">32.6k</strong></div><div><p class="small muted" style="margin:0 0 7px">输出</p><strong style="font-size:16px;font-weight:550">6.2k</strong></div><div><p class="small muted" style="margin:0 0 7px">缓存</p><strong style="font-size:16px;font-weight:550">18.4k</strong></div></div><div class="divider" style="margin:17px 0"></div><div style="display:flex;justify-content:space-between;font-size:12px"><span class="muted">合计 57.2k tokens</span><strong style="font-weight:550">$0.0428</strong></div></div><div data-fd-id="dialog-context-autocompact">${row('自动压缩上下文','接近窗口上限时，压缩历史内容以继续对话。',`<span data-setting="autoCompact">${toggle(true)}</span>`)}</div><p class="small muted" data-fd-editable="true" style="line-height:1.7;margin:0">用量与费用为本次会话的累计值。</p></div>`,
    },
    sessionMenu: {
      title: '会话操作',
      html: () => `<div data-fd-id="dialog-session-menu"><div class="notice" style="margin-bottom:16px"><strong data-fd-editable="true" style="font-size:13px;font-weight:550">设计 OWL 工作区</strong><p class="small muted" style="margin:5px 0 0">owl-mono · 刚刚更新</p></div><div class="menu-list" style="border:1px solid var(--border);border-radius:12px;overflow:hidden">${menuItem('dialog-session-pin','pin','置顶会话','pin','在侧边栏的置顶分组中快速找到。')}${menuItem('dialog-session-archive','archive','归档会话','archive','收起到归档列表，可随时恢复。')}<div class="divider"></div>${menuItem('dialog-session-delete','trash','删除会话','open-modal','永久删除这份会话记录。','delete',false,true)}</div></div>`,
    },
    projectMenu: {
      title: '项目操作',
      html: () => `<div data-fd-id="dialog-project-menu"><div class="notice" style="display:flex;align-items:center;gap:12px;margin-bottom:16px">${icon('folder',24)}<div><strong data-fd-editable="true" style="font-size:13px;font-weight:550">owl-mono</strong><p class="small muted" style="margin:5px 0 0">D:\\owl\\owl-re-v1\\owl-mono</p></div></div><div class="menu-list" style="border:1px solid var(--border);border-radius:12px;overflow:hidden">${menuItem('dialog-project-new-chat','plus','新建会话','new-chat','在当前项目中开始新的对话。')}${menuItem('dialog-project-pin','pin','置顶项目','pin','在置顶分组中保留项目入口。')}${menuItem('dialog-project-reveal','folder','在资源管理器中打开','reveal')}</div></div>`,
    },
    projectSwitch: {
      title: '切换项目',
      html: () => `<div data-fd-id="dialog-project-switch"><p class="small muted" data-fd-editable="true" style="margin:0 0 16px;line-height:1.7">切换工作目录后，会从新的会话开始。</p><div class="menu-list" style="border:1px solid var(--border);border-radius:12px;overflow:hidden">${menuItem('dialog-project-current','folder','owl-mono','choose-project','D:\\owl\\owl-re-v1\\owl-mono','owl-mono',true)}${menuItem('dialog-project-demo','folder','demo-app','choose-project','D:\\work\\demo-app','demo-app')}<div class="divider"></div>${menuItem('dialog-project-add','plus','添加项目…','open-modal','','project')}</div></div>`,
    },
    sectionMenu: {
      title: '侧边栏排序',
      html: () => `<div class="form-stack" data-fd-id="dialog-section-menu"><div><p class="small muted" data-fd-editable="true" style="margin:0 0 10px">置顶分组</p><div class="menu-list" style="border:1px solid var(--border);border-radius:12px;overflow:hidden">${menuItem('dialog-sort-pinned-manual','list','按置顶顺序','sort','按先后顺序排列。','pinned:manual',true)}${menuItem('dialog-sort-pinned-recent','clock','最近更新','sort','','pinned:recent')}</div></div><div><p class="small muted" data-fd-editable="true" style="margin:0 0 10px">最近分组</p><div class="menu-list" style="border:1px solid var(--border);border-radius:12px;overflow:hidden">${menuItem('dialog-sort-recent-time','clock','按最近更新','sort','','recent:recent',true)}${menuItem('dialog-sort-recent-name','list','按名称','sort','','recent:name')}</div></div></div>`,
    },
    location: {
      title: '运行位置',
      html: () => `<div data-fd-id="dialog-location"><div class="menu-list" style="border:1px solid var(--border);border-radius:12px;overflow:hidden">${menuItem('dialog-location-local','monitor','本地 · 此电脑','close-modal','已连接到本地工作环境。','local',true)}<div class="menu-item" style="display:flex;align-items:center;gap:12px;padding:14px;opacity:.55" aria-disabled="true">${icon('cloud',18)}<span style="flex:1;font-size:13px">远程会话</span>${tag('暂不可用')}</div></div></div>`,
    },
    delete: {
      title: '删除这份会话？',
      html: () => `<div class="form-stack" data-fd-id="dialog-delete-content"><div class="notice warning" style="display:flex;gap:12px;align-items:flex-start">${icon('trash',21)}<p data-fd-editable="true" style="margin:0;font-size:13px;line-height:1.7">「设计 OWL 工作区」的聊天记录将被永久删除，此操作不可恢复。</p></div><p class="small muted" data-fd-editable="true" style="margin:0;line-height:1.7">如果暂时不需要这份会话，可以先归档，之后仍可恢复。</p></div><div style="display:flex;justify-content:space-between;gap:12px;margin-top:24px;padding-top:18px;border-top:1px solid var(--border)">${button('改为归档','archive','ghost')}<div style="display:flex;gap:8px">${button('取消','close-modal','ghost')}${button('永久删除','delete-confirm','danger')}</div></div>`,
    },
    providerAdd: {
      title: '添加供应商',
      html: () => `<div class="form-stack" data-fd-id="dialog-provider-add"><p class="small muted" data-fd-editable="true" style="margin:0;line-height:1.7">填写服务地址与认证信息，再为它添加模型。</p><div class="settings-grid" style="display:grid;grid-template-columns:1fr 1fr;gap:16px">${field('供应商 ID *','字母或数字开头，可含 . _ -',input('demo-provider','如 demo-provider'))}${field('显示名','用于界面展示',input('我的模型服务','如 我的模型服务'))}</div>${field('Base URL *','供应商提供的接口地址',input('https://api.example.com/v1','https://…'))}${field('API 协议 *','根据供应商的接口格式选择',select(['OpenAI 兼容 · Completions','Anthropic 兼容 · Messages','OpenAI Responses']))}${field('API Key','也可填写 $环境变量名',`<input class="input" type="password" value="sk-demo-only-not-a-real-secret" aria-label="API Key" placeholder="粘贴 API Key 或 $环境变量名" autocomplete="off" style="width:100%">`)}</div><div style="display:flex;justify-content:space-between;gap:12px;margin-top:24px;padding-top:18px;border-top:1px solid var(--border)">${button('清空','provider-clear','ghost')}<div style="display:flex;gap:8px">${button('取消','close-modal','ghost')}${button('保存供应商','provider-add','primary')}</div></div>`,
    },
    modelAdd: {
      title: '添加模型',
      html: () => `<div class="form-stack" data-fd-id="dialog-model-add"><div class="notice" style="display:flex;align-items:center;justify-content:space-between"><span class="small muted">添加到供应商</span><strong data-fd-editable="true" style="font-size:13px;font-weight:550">我的模型服务</strong></div><div class="settings-grid" style="display:grid;grid-template-columns:1fr 1fr;gap:16px">${field('模型 ID *','接口请求使用的模型名称',input('owl-coder','如 owl-coder'))}${field('显示名','用于模型选择菜单',input('主力编码模型','如 主力编码模型'))}${field('上下文窗口','单位：tokens',`<input class="input" type="number" min="1" value="128000" aria-label="上下文窗口" style="width:100%">`)}${field('最大输出','单位：tokens',`<input class="input" type="number" min="1" value="8192" aria-label="最大输出" style="width:100%">`)}</div>${row('推理模型','允许在输入栏中选择思考强度。',toggle(true))}</div>${footer('保存模型','model-add')}`,
    },
    oauth: {
      title: '连接你的账号',
      html: () => `<div class="form-stack" data-fd-id="dialog-oauth"><div style="display:flex;align-items:center;gap:12px"><span style="display:grid;place-items:center;width:42px;height:42px;border:1px solid var(--border);border-radius:12px">${icon('key',22)}</span><div><strong data-fd-editable="true" style="font-size:14px;font-weight:550">通过浏览器登录</strong><p class="small muted" data-fd-editable="true" style="margin:5px 0 0">选择厂商，然后完成账号授权。</p></div></div>${field('厂商','可用登录方式由厂商决定',select(['选择厂商…','支持浏览器登录的厂商','支持 API Key 的厂商']))}${row('GitHub 企业版','登录时填写企业域名。',toggle(false))}<div class="notice" style="font-size:12px;line-height:1.8" data-fd-editable="true">浏览器打开后，按照页面提示完成登录。授权成功后，OWL 会显示连接结果。</div><details data-fd-id="dialog-oauth-api-key"><summary class="small muted" style="cursor:pointer">使用 API Key 连接</summary><div style="margin-top:12px;display:flex;gap:8px"><input class="input" type="password" aria-label="快捷接入 API Key" placeholder="粘贴 API Key…" style="flex:1;min-width:0">${button('保存','save','primary')}</div></details><details data-fd-id="dialog-oauth-manual-code"><summary class="small muted" style="cursor:pointer">登录需要手动输入验证码？</summary><div style="margin-top:12px">${field('授权码或登录信息','根据登录流程给出的提示填写',input('','输入浏览器提供的授权码…'))}<div style="text-align:right;margin-top:12px">${button('提交','auth-respond','primary')}</div></div></details></div><div style="display:flex;justify-content:space-between;gap:8px;margin-top:24px;padding-top:18px;border-top:1px solid var(--border)">${button('取消登录','auth-cancel','ghost')}${button('继续到浏览器','oauth','primary')}</div>`,
    },
    authSuccess: {
      title: '账号已连接',
      html: () => `<div data-fd-id="dialog-auth-success" style="text-align:center;padding:10px 0 0"><div style="display:grid;place-items:center;width:54px;height:54px;margin:0 auto 17px;border-radius:50%;background:var(--accent-soft);color:var(--accent,#2f9e5a)">${icon('check',26)}</div><h3 data-fd-editable="true" style="font-size:17px;font-weight:600;margin:0 0 10px">连接成功</h3><p class="small muted" data-fd-editable="true" style="margin:0;line-height:1.8">认证信息已保存。你可以继续添加模型，或回到对话工作区。</p><div style="display:flex;justify-content:center;gap:8px;margin-top:24px">${button('返回设置','close-modal','ghost')}${button('添加模型','open-model-add','primary')}</div></div>`,
    },
    providerDelete: {
      title: '删除这个供应商？',
      html: () => `<div class="form-stack" data-fd-id="dialog-provider-delete"><div class="notice warning"><p data-fd-editable="true" style="font-size:13px;line-height:1.7;margin:0">删除「我的模型服务」后，它下方的全部模型也会一并移除。</p></div><p class="small muted" data-fd-editable="true" style="margin:0">需要再次使用时，可以重新添加供应商与模型。</p></div>${footer('删除供应商','provider-delete-confirm',true)}`,
    },
  };
})();
