const DEMO = {view:'home',pane:'files',settings:'general',modal:null,dock:'right',sidebar:true,running:false,model:'默认模型',mode:'标准模式',thinking:'中',status:'normal',focus:false,split:false,questionNav:false,shot:false,desktopMenu:null};
const settingsOrder = ['general','providers','plugins','appearance','prompts','archive','json','about'];
const paneOrder = ['files','changes','editor','terminal','browser','tasks','impression','sidechat','image'];
const paneIcons = {files:'folder',changes:'git',editor:'code',terminal:'terminal',browser:'browser',tasks:'clock',impression:'leaf',sidechat:'chat',image:'image'};
const settingsIcons = {general:'settings',providers:'code',plugins:'plus',appearance:'image',prompts:'chat',archive:'clock',json:'code',about:'leaf'};
const params = new URLSearchParams(location.search);
if(params.get('view')) {const v=params.get('view');if(v.startsWith('settings-')){DEMO.view='settings';DEMO.settings=v.slice(9)}else if(paneOrder.includes(v)){DEMO.view='workspace';DEMO.pane=v;}else DEMO.view=v;}
if(params.get('modal'))DEMO.modal=params.get('modal');
if(params.get('dock'))DEMO.dock=params.get('dock');
if(params.has('focus'))DEMO.focus=true;
if(params.has('split')){DEMO.split=true;DEMO.focus=true;}
if(params.has('navigator'))DEMO.questionNav=true;
if(params.has('shot'))DEMO.shot=true;
const artwork = '__OWL_SVG__';
function mark(){return `<span class="brand-mark">${artwork}</span>`;}
function desktopTitlebar(){const menus={file:[['新会话','view-home'],['打开项目…','dialog-project']],edit:[['复制','copy-demo']],view:[['显示 / 隐藏会话列表','toggle-sidebar'],['右侧工作台','dock-right'],['底部工作台','dock-bottom']],help:[['关于 OWL','settings-about']]};return `<header class="desktop-titlebar" data-fd-id="section-desktop-titlebar"><div class="desktop-menu-row">${iconButton('panel','toggle-sidebar','显示 / 隐藏会话列表')}${[['file','文件'],['edit','编辑'],['view','视图'],['help','帮助']].map(([key,title])=>`<button class="desktop-menu-trigger ${DEMO.desktopMenu===key?'active':''}" data-action="desktop-menu" data-menu="${key}" data-fd-id="menu-${key}" aria-expanded="${DEMO.desktopMenu===key}">${title}</button>`).join('')}</div><span class="desktop-app-name">OWL</span><div class="desktop-window-controls" data-fd-id="section-window-controls"><button data-action="window-minimize" title="最小化" aria-label="最小化"><svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor"><path d="M2 6h8"/></svg></button><button data-action="window-maximize" title="最大化 / 还原" aria-label="最大化 / 还原"><svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor"><rect x="2" y="2" width="8" height="8" rx=".5"/></svg></button><button class="window-close" data-action="window-close" title="关闭" aria-label="关闭">${icon('close',14)}</button></div>${DEMO.desktopMenu?`<div class="desktop-menu-popover" data-fd-id="desktop-menu-${DEMO.desktopMenu}" role="menu">${menus[DEMO.desktopMenu].map(([title,action])=>`<button role="menuitem" data-action="${action}">${title}</button>`).join('')}</div>`:''}</header>`;}
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function icon(name,size=18){const paths={folder:'<path d="M3 7V5a2 2 0 0 1 2-2h5l3 3h6a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z"/>',chat:'<path d="M21 11a8 8 0 0 1-8 8H5l-3 3V11a9 9 0 0 1 19 0Z"/><path d="M7 10h10M7 14h6"/>',settings:'<path d="m10 3-1 3-3 1-3-1-1 4 3 2v3l-2 3 3 3 3-2 3 1 1 3 4-1 1-3 3-1 3 1 1-4-3-2v-3l2-3-3-3-3 2-3-1-1-3-4 1Z" transform="scale(.83) translate(2 0)"/><circle cx="12" cy="12" r="3"/>',code:'<path d="m8 6-6 6 6 6m8-12 6 6-6 6M14 4l-4 16"/>',terminal:'<rect x="2" y="4" width="20" height="16" rx="3"/><path d="m6 9 3 3-3 3m6 0h6"/>',git:'<circle cx="6" cy="5" r="2"/><circle cx="18" cy="6" r="2"/><circle cx="6" cy="19" r="2"/><path d="M6 7v10m0-4c8 0 12-2 12-5"/>',browser:'<circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2c6 5 6 15 0 20-6-5-6-15 0-20Z"/>',check:'<path d="m5 12 4 4 10-10"/>',plus:'<path d="M12 5v14M5 12h14"/>',arrow:'<path d="M12 20V4m-6 6 6-6 6 6"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',shield:'<path d="M12 2 3 6v6c0 5 6 8 9 10 3-2 9-5 9-10V6l-9-4Z"/><path d="m8 12 3 3 5-6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',chevron:'<path d="m9 5 7 7-7 7"/>',image:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="9" cy="8" r="1.5"/><path d="m3 17 6-6 4 4 3-3 5 5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/>',leaf:'<path d="M20 3C7 2 1 10 5 16s15 4 15-13Zm-1 1L4 20"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M15 8V3H3v12h5"/>',refresh:'<path d="M21 8V3l-3 3a9 9 0 1 0 2 11M21 8h-5"/>',panel:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M9 4v16"/>',bottom:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 14h18"/>'};return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.code}</svg>`;}
function button(text,action,cls=''){return `<button type="button" class="btn ${cls}" data-action="${action}" data-fd-id="btn-${action}">${text}</button>`;}
function input(value,placeholder=''){return `<input class="input" value="${esc(value)}" placeholder="${esc(placeholder)}"/>`;}
function select(opts){return `<select class="select">${opts.map(o=>`<option>${esc(o)}</option>`).join('')}</select>`;}
function toggle(on=true){return `<button class="switch" role="switch" aria-checked="${on}" data-action="toggle" aria-label="切换选项"></button>`;}
function tag(t,tone=''){return `<span class="tag ${tone}">${t}</span>`;}
function field(label,desc,control){return `<div class="field"><label>${label}</label>${control}<span class="field-desc">${desc}</span></div>`;}
function row(title,desc,control){return `<div class="row"><div><div class="row-title">${title}</div><div class="row-description">${desc}</div></div>${control}</div>`;}
function sectionHead(title,desc=''){return `<div class="section-heading"><h3>${title}</h3>${desc?`<p>${desc}</p>`:''}</div>`;}
function iconButton(name,action,title,active=false){return `<button class="icon-btn ${active?'active':''}" data-action="${action}" aria-label="${title}" title="${title}" data-fd-id="btn-${action}">${icon(name,17)}</button>`;}
function rail(){return `<nav class="rail" data-fd-id="section-activity-rail" aria-label="主导航">${mark()}<div style="height:11px"></div>${iconButton('chat','view-home','会话',DEMO.view!=='settings')}${iconButton('settings','settings-general','设置',DEMO.view==='settings')}<div style="margin-top:auto">${iconButton('leaf','settings-about','关于 OWL')}</div></nav>`;}
function sidebar(){return `<aside class="sidebar ${!DEMO.sidebar?'hide':''}" data-fd-id="section-session-sidebar"><div class="sidebar-brand">owl<small>LOCAL</small></div><label class="sidebar-search">${icon('search',14)}<input placeholder="搜索会话" aria-label="搜索会话" data-action="search-session"/><span class="key">⌘ K</span></label>${button(icon('plus',15)+' 新会话','view-home','new-chat')}<div class="nav-section"><span>置顶</span>${iconButton('more','dialog-sectionMenu','分组操作')}</div><button class="nav-row" data-action="view-chat" data-fd-id="row-pinned-session">${icon('chat',14)}<span class="clip">梳理项目架构</span>${icon('more',14)}</button><div class="nav-section" style="margin-top:15px"><span>项目</span>${iconButton('plus','dialog-project','添加项目')}</div><button class="nav-row" data-action="dialog-projectMenu" data-fd-id="row-current-project">${icon('chevron',10)}${icon('folder',15)}<span class="clip">owl-mono</span>${tag('当前','green')}</button><div class="nested"><button class="nav-row ${DEMO.view!=='home'?'active':''}" data-action="view-chat" data-fd-id="row-design-session">${icon('chat',13)}<span class="clip" data-fd-editable="text" data-fd-id="text-current-session">重新设计工作台界面</span><span class="dot"></span></button><button class="nav-row" data-action="view-chat">${icon('chat',13)}<span class="clip">检查设置页交互</span></button></div><button class="nav-row" data-action="dialog-projectSwitch">${icon('chevron',10)}${icon('folder',15)}<span class="clip">Owl-def</span></button><div class="nav-section" style="margin-top:22px"><span>最近会话</span>${iconButton('more','dialog-sessionMenu','会话操作')}</div><button class="nav-row" data-action="view-chat">${icon('chat',14)}<span class="clip">理解权限确认流程</span></button><button class="nav-row" data-action="view-chat">${icon('chat',14)}<span class="clip">整理用户印象</span></button><button class="nav-row" data-action="view-chat">${icon('chat',14)}<span class="clip">检查本地开发环境</span></button><div class="sidebar-foot"><span class="avatar">L</span><div><div style="font-weight:550;font-size:12px">本地工作空间</div><div class="tiny">所有会话保存在本机</div></div>${iconButton('settings','settings-general','打开设置')}</div></aside>`;}
function chrome(){return `<header class="chrome" data-fd-id="section-chat-header">${iconButton('panel','toggle-sidebar','收起会话列表')}<span class="title" data-fd-id="text-session-header" data-fd-editable="text">${DEMO.view==='home'?'新会话':'重新设计工作台界面'}</span><span class="muted">/</span><span class="muted small" style="display:flex;align-items:center;gap:6px">${icon('folder',13)} owl-mono</span><div class="chrome-actions"><span class="connection-dot" title="本地已连接"></span><span class="small muted" style="margin-right:12px">本地</span>${iconButton('bottom','dock-bottom','停靠到底部',DEMO.view==='workspace'&&DEMO.dock==='bottom')}${iconButton('panel','dock-right','停靠到右侧',DEMO.view==='workspace'&&DEMO.dock==='right')}<span style="height:17px;width:1px;background:var(--border);margin:0 5px"></span>${iconButton('more','dialog-sessionMenu','更多会话操作')}</div></header>`;}
function home(){return `<div class="hero" data-fd-id="section-start-page">${mark()}<span class="tiny" style="letter-spacing:.12em;margin-bottom:8px">YOUR LOCAL CODING COMPANION</span><h1 data-fd-id="text-welcome" data-fd-editable="text">让想法，在这里落地。</h1><p data-fd-id="text-welcome-subtitle" data-fd-editable="text">从一个问题、一段代码，或一个待完成的任务开始。</p><div class="quick-links">${[['folder','files','浏览项目文件','熟悉项目与代码'],['git','changes','查看文件变动','审阅每一处修改'],['browser','browser','打开浏览器','查看页面与效果']].map(([ico,key,title,desc])=>`<button class="quick-link" data-action="pane-${key}" data-fd-id="card-quick-${key}">${icon(ico,22)}<span>${title}</span><small class="muted">${desc}</small></button>`).join('')}</div><div class="quick-secondary">${button(icon('terminal',14)+' 终端','pane-terminal','ghost')}${button(icon('clock',14)+' 执行记录','pane-tasks','ghost')}${button(icon('chat',14)+' 侧边对话','pane-sidechat','ghost')}${button(icon('leaf',14)+' 用户印象','pane-impression','ghost')}</div></div>`;}
function chat(){const state=DEMO.status;return `<div class="chat-content" data-fd-id="section-chat-stream">${state==='offline'?`<div class="notice warning" style="margin-bottom:23px" data-fd-id="notice-disconnected">连接已断开，正在重连… ${button('重新连接','state-normal','ghost')}</div>`:''}<div class="chat-message user-message" data-fd-id="message-user"><p data-fd-id="text-user-prompt" data-fd-editable="text">帮我梳理 OWL 工作台的布局，让聊天、文件和代码变动更清楚。</p></div><div class="assistant-heading">${mark()}<span>owl</span>${tag(DEMO.running?'正在处理':'已完成',DEMO.running?'warning':'green')}<span class="tiny" style="margin-left:auto">16:24</span></div><div class="assistant-copy" data-fd-id="message-assistant"><p data-fd-id="text-answer-lead" data-fd-editable="text">我检查了工作台的结构。聊天负责推进任务，右侧面板负责查看文件和验证结果；这两部分应该始终保持清楚的边界。</p><div class="tool-group" data-fd-id="section-tool-activity"><details open><summary class="tool-summary"><span style="display:flex;align-items:center;gap:7px">${icon('check',15)} 已检查 3 个文件</span><span class="tiny">收起 ${icon('chevron',10)}</span></summary><div class="tool-line">${icon('check',13)} 读取 <span class="code">App.tsx</span><span class="tiny" style="margin-left:auto">完成</span></div><div class="tool-line">${icon('check',13)} 读取 <span class="code">Workbench.tsx</span><span class="tiny" style="margin-left:auto">完成</span></div><details><summary class="tool-line">${icon('terminal',13)} 查看当前工作区<span class="tiny" style="margin-left:auto">查看输出 ${icon('chevron',10)}</span></summary><pre class="code" style="margin:4px 0;padding:10px;background:var(--color-owl-bg);border-radius:6px">apps/desktop/src\n  components/\n  sidebar/\n  theme.ts</pre></details></details></div><p data-fd-id="text-answer-suggestion" data-fd-editable="text">建议将当前项目、会话和执行状态放在固定位置，让每一步操作都有明确的上下文：</p><ol><li><strong>左侧导航</strong>：项目与会话清晰分组，当前会话用轻量选中态。</li><li><strong>聊天区域</strong>：回复保持舒适行宽，工具过程默认显示摘要。</li><li><strong>工作台</strong>：统一标签与工具栏，文件变动留出完整预览空间。</li></ol><div class="notice" data-fd-id="notice-design-only" style="margin-top:16px">${icon('shield',14)} 当前仅展示设计原型，业务代码将在你确认后修改。</div></div><div class="chat-meta">${iconButton('copy','copy-demo','复制回答')}${button('查看相关文件','pane-files','ghost')}<span>3 个文件 · 12.4k tokens</span><span style="margin-left:auto">${button('操作菜单','dialog-sessionMenu','ghost')}</span></div>${state==='error'?`<div class="notice warning" style="margin-top:18px" data-fd-id="notice-tool-error"><strong>命令执行失败</strong><p>找不到目标路径。请检查工作目录后重试。</p>${button('查看错误详情','pane-tasks','ghost')}</div>`:''}</div>`;}
function composer(){return `<div class="composer-zone" data-fd-id="section-composer">${DEMO.view!=='home'?`<div class="todo-pin" data-fd-id="section-todo-pin" data-action="dialog-todo">${icon('check',14)}<span>任务进度 <strong>2 / 3</strong></span><span class="muted">正在整理设计建议</span><span class="progress"></span>${icon('chevron',11)}</div>`:''}<div class="composer"><div class="composer-top">${button(icon('folder',13)+' owl-mono','dialog-projectSwitch','ghost')}${button('+ 项目','dialog-project','ghost')}<span style="margin-left:auto;display:flex;gap:5px;align-items:center">${icon('shield',12)} 本地工作空间</span></div><textarea placeholder="描述你的需求，或输入你想了解的问题…" rows="2" aria-label="输入消息" data-fd-id="field-chat-input" data-fd-editable="value"></textarea><div class="composer-footer">${button(icon('shield',13)+` ${DEMO.mode}`,'dialog-mode','ghost')}${button(`${DEMO.model} ▾`,'dialog-model','ghost')}${button(`思考 · ${DEMO.thinking}`,'dialog-thinking','ghost')}${button('<span class="connection-dot"></span> 24%','dialog-context','ghost')}<button class="send" data-action="send-demo" title="${DEMO.running?'停止':'发送'}" aria-label="${DEMO.running?'停止':'发送'}" data-fd-id="btn-send">${DEMO.running?'<span style="width:10px;height:10px;border-radius:2px;background:white"></span>':icon('arrow',17)}</button></div></div><div class="composer-hint">Enter 发送 <span style="margin:0 7px">·</span> Shift + Enter 换行 <span style="margin:0 7px">·</span> 请审阅 OWL 的关键操作</div></div>`;}
function workbench(){const pane=window.OWL_PANES[DEMO.pane]||window.OWL_PANES.files;return `<aside class="workbench" data-fd-id="section-workbench"><div class="workbench-bar"><div class="workbench-tools">${paneOrder.map(k=>iconButton(paneIcons[k],'pane-'+k,window.OWL_PANES[k]?.title||k,DEMO.pane===k)).join('')}</div>${iconButton(DEMO.dock==='right'?'bottom':'panel','dock-'+(DEMO.dock==='right'?'bottom':'right'),'切换停靠位置')}${iconButton('close','close-workbench','收起工作台')}</div><div class="pane-toolbar" style="height:44px"><span style="font-weight:600;display:flex;align-items:center;gap:7px">${icon(paneIcons[DEMO.pane],14)} ${pane.title}</span>${DEMO.pane==='editor'?'<span class="tiny">App.tsx</span>':''}<span class="tiny" style="margin-left:auto">owl-mono</span></div><div class="workbench-body" data-fd-id="pane-${DEMO.pane}">${pane.html()}</div></aside>`;}
function settings(){const cfg=window.OWL_SETTINGS[DEMO.settings]||window.OWL_SETTINGS.general;return `<div class="settings-frame" data-fd-id="section-settings"><div class="settings-top">${button('← 返回工作台','view-chat','ghost')}<span style="height:18px;width:1px;background:var(--border)"></span><h2>设置</h2><span class="tiny" style="margin-left:auto">你的本地 OWL 偏好</span></div><div class="settings-layout"><nav class="settings-nav" aria-label="设置导航" data-fd-id="settings-navigation"><div class="nav-section" style="margin-bottom:8px">工作空间</div>${settingsOrder.map((k,i)=>`${i===6?'<div class="nav-section" style="margin-top:17px">高级</div>':''}<button class="nav-row ${DEMO.settings===k?'active':''}" data-action="settings-${k}" data-fd-id="tab-settings-${k}">${icon(settingsIcons[k],17)}${window.OWL_SETTINGS[k]?.title||k}</button>`).join('')}<div class="notice" style="margin-top:40px;font-size:11px;padding:12px">${icon('shield',16)}<p style="margin-top:7px">偏好与会话保存在本机，你可以随时调整。</p></div></nav><div class="settings-area"><div class="settings-heading"><div><h1 data-fd-id="text-settings-title">${cfg.title}</h1><p data-fd-id="text-settings-description" data-fd-editable="text">${cfg.description||'按你的工作方式配置 OWL。'}</p></div>${tag(DEMO.settings==='appearance'?'立即生效':DEMO.settings==='archive'?'会话管理':'本地配置','green')}</div><main class="settings-content">${cfg.html()}</main><div class="settings-footer" data-fd-id="settings-save-footer"><span class="hint" data-fd-id="settings-save-status">${DEMO.settings==='appearance'?'选择主题后立即生效。':'设置示例仅用于预览；你可以编辑并导出设计意见。'}</span>${button('关闭','view-chat','ghost')}${['appearance','about'].includes(DEMO.settings)?'':button('保存更改','save','primary')}</div></div></div></div>`;}
function dialogsGallery(){const list=[['project','添加项目','选择或创建本地工作目录','folder'],['model','模型选择','供应商、模型与上下文信息','code'],['mode','执行模式','标准、计划与自动模式','shield'],['permission','操作确认','命令详情与允许 / 拒绝','shield'],['question','Agent 提问','逐题作答与自由补充','chat'],['questionMulti','多选提问','选项、备注与多题进度','chat'],['providerAdd','添加供应商','地址、协议与凭据','code'],['modelAdd','添加模型','模型 ID 与能力配置','code'],['context','上下文用量','Tokens、缓存与费用','clock'],['sessionMenu','会话操作','置顶、归档与删除','chat'],['delete','删除确认','对象名称与明确操作结果','close'],['filePicker','网页选择文件','本机路径与多文件选择','folder'],['todo','任务清单','当前任务、完成进度','check'],['oauth','浏览器登录','设备码与登录进度','browser'],['authSuccess','连接成功','授权结果与下一步','check']];return `<main class="dialog-gallery"><span class="tiny">INTERACTION LIBRARY</span><h1 style="margin:5px 0 8px">每一步，都有清楚的反馈。</h1><p class="muted">统一弹窗、菜单与关键状态，点击任意卡片查看完整效果。</p><div class="dialog-grid">${list.map(([k,title,desc,i])=>`<button class="dialog-tile" data-action="dialog-${k}" data-fd-id="card-dialog-${k}"><span class="green">${icon(i,22)}</span><h3>${title}</h3><p class="muted">${desc}</p></button>`).join('')}</div><div class="state-strip">${button('正常会话','state-normal')}${button('运行中','state-running')}${button('连接中断','state-offline')}${button('工具失败','state-error')}${button('空状态','state-empty')}${button('编辑器外部变更','state-stale')}</div></main>`;}
function specialDialog(k){if(k==='screenshot')return {title:'最新页面截图',html:()=>OWL_PANES.image.html()};if(k==='todo')return {title:'当前任务',html:()=>`<p class="muted small" style="margin-bottom:20px">重新设计工作台界面 · 2 / 3 已完成</p>${row('核对页面与功能','已完成',tag('完成','green'))}${row('统一视觉层级','已完成',tag('完成','green'))}${row('整理全部界面原型','正在进行',tag('进行中'))}<div style="margin-top:24px;text-align:right">${button('返回对话','close-modal','primary')}</div>`};if(k==='filePicker')return {title:'网页请求选择文件',html:()=>`${field('本机文件路径','多个文件使用 | 分隔。',`<input class="input" value="D:\\owl\\screenshots\\preview.png" data-fd-id="field-browser-file-path" data-fd-editable="value"/>`)}<div class="notice">目标网页将读取你选择的文件，请确认路径后继续。</div><div style="display:flex;gap:10px;justify-content:end;margin-top:22px">${button('忽略','close-modal','ghost')}${button('提交选择','browser-file-submit','primary')}</div>`};if(k==='fileContext')return {title:'文件操作 · App.tsx',html:()=>`<div class="menu-list">${[['code','打开编辑器','pane-editor'],['folder','在资源管理器中显示','demo-feedback'],['copy','复制相对路径','copy-demo'],['copy','复制完整路径','copy-demo'],['code','在 VS Code 中打开','demo-feedback'],['code','重命名','dialog-rename'],['close','删除','dialog-deleteFile']].map(([i,t,a])=>button(icon(i,16)+' '+t,a,'ghost')).join('')}</div>`};return null;}
function modal(){const k=DEMO.modal;if(!k)return '';const dlg=specialDialog(k)||window.OWL_PANE_DIALOGS?.[k]||window.OWL_SETTINGS_DIALOGS?.[k]||window.OWL_DIALOGS?.[k];if(!dlg)return '';return `<div class="modal-shade" data-fd-id="modal-${k}"><section class="product-modal" role="dialog" aria-modal="true" aria-label="${dlg.title}"><div class="modal-heading"><h2>${dlg.title}</h2>${iconButton('close','close-modal','关闭弹窗')}</div><div class="modal-content">${dlg.html()}</div></section></div>`;}
let editedValues=new Map();
function restoreComments(){if(typeof comments==='undefined')return;for(const c of comments){if(!c.anchorFdId)continue;document.querySelectorAll(`[data-fd-id="${c.anchorFdId}"]`).forEach(el=>el.setAttribute('data-fd-comment-target',c.targetAttr||'c'+c.id));}renderMarkers();}
function enhance(mount){
 const screen=mount.querySelector('.owl-screen');screen.classList.toggle('is-home',DEMO.view==='home');
 const body=document.createElement('div');body.className='desktop-body';
 for(const child of Array.from(screen.children)){if(!child.classList.contains('modal-shade'))body.appendChild(child);}
 screen.prepend(body);screen.insertAdjacentHTML('afterbegin',desktopTitlebar());
 const side=mount.querySelector('.sidebar');if(side){const list=document.createElement('div');list.className='sidebar-scroll';const foot=side.querySelector('.sidebar-foot');let collecting=false;for(const child of Array.from(side.children)){if(child.classList.contains('nav-section'))collecting=true;if(collecting&&child!==foot)list.appendChild(child);}side.insertBefore(list,foot);}
 const split=mount.querySelector('.body-split');if(split)split.classList.toggle('focused',DEMO.focus);
 const wb=mount.querySelector('.workbench');if(wb){wb.insertAdjacentHTML('afterbegin','<div class="resize-handle" data-resize-pane title="拖动调整工作台尺寸"></div>');const heading=wb.querySelector(':scope > .pane-toolbar');heading.insertAdjacentHTML('beforeend',button(DEMO.focus?'返回聊天':'展开','focus-workbench','ghost pane-focus')+button(DEMO.split?'合并':'分屏','split-workbench','ghost'));if(DEMO.split){wb.querySelector('.workbench-body').innerHTML=`<div class="split-panes"><div>${OWL_PANES.files.html()}</div><div>${OWL_PANES[DEMO.pane==='files'?'editor':DEMO.pane].html()}</div></div>`;}}
 const actions=mount.querySelector('.chrome-actions');if(actions){actions.insertAdjacentHTML('afterbegin',iconButton('chat','toggle-question-nav','提问导航')+iconButton('image','toggle-shot-preview','最新截图'));const local=actions.querySelector('.connection-dot');if(local){const chip=document.createElement('button');chip.className='toolbar-local';chip.dataset.action='dialog-location';chip.setAttribute('aria-label','本地运行状态');const label=local.nextElementSibling;chip.appendChild(local);if(label)chip.appendChild(label);actions.prepend(chip);}actions.querySelectorAll(':scope > span[style*="height:17px"]').forEach(e=>e.remove());const toggle=mount.querySelector('.chrome>[data-action="toggle-sidebar"]');if(toggle)toggle.remove();}
 const convo=mount.querySelector('.conversation');if(convo&&DEMO.questionNav)convo.insertAdjacentHTML('beforeend',`<aside class="question-nav" data-fd-id="section-question-navigator"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px"><span class="small">提问导航 · 1</span>${iconButton('close','toggle-question-nav','收起提问导航')}</div><button class="nav-row active" data-action="jump-question" style="align-items:flex-start"><span class="tag green">1</span><span><strong>重新设计工作台界面</strong><br><span class="muted" style="line-height:1.6">聊天、文件和代码变动更清楚。</span></span></button></aside>`);
 if(convo&&DEMO.shot)convo.insertAdjacentHTML('beforeend',`<div class="shot-preview" data-fd-id="section-latest-screenshot"><div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:7px"><span class="tiny">最新截图</span>${iconButton('close','toggle-shot-preview','关闭截图缩略图')}</div><button style="border:0;background:var(--color-owl-bg);border-radius:5px;width:100%;height:95px;display:flex;align-items:center;justify-content:center;gap:9px" data-action="dialog-screenshot">${mark()}<span class="small muted">页面效果</span></button></div>`);
 const group=mount.querySelector('.tool-group');if(group){group.insertAdjacentHTML('beforebegin',`<details style="margin:10px 0 14px;color:var(--color-owl-faint);font-size:11px" data-fd-id="section-thinking-process"><summary style="display:flex;align-items:center;gap:7px">${icon('leaf',13)} 思考过程 · 2 行 ${icon('chevron',10)}</summary><div class="code" style="padding:12px;border-left:1px solid var(--border);margin:9px 0">先核对已有页面能力，再整理导航、内容与操作的层级。确保每项现有功能都有对应设计。</div></details>`);const output=group.querySelector('pre');if(output)output.insertAdjacentHTML('afterend',`<details data-fd-id="section-tool-full-output"><summary class="small green" style="margin:8px 0">查看完整输出（共 24 行）</summary><pre class="code" style="max-height:220px;overflow:auto;border-left:1px solid var(--border);padding:10px">${Array.from({length:24},(_,i)=>`${String(i+1).padStart(2,'0')}  项目文件索引 · 示例输出`).join('\n')}</pre></details>`);}
 const user=mount.querySelector('.user-message');if(user){user.style.position='relative';user.insertAdjacentHTML('afterbegin','<span data-fd-id="step-number-1" style="position:absolute;left:-40px;top:15px;display:grid;place-items:center;width:25px;height:25px;border-radius:50%;background:var(--accent-soft);color:var(--accent);font-size:11px">1</span>');}
 const menu=mount.querySelector('.dialog-grid');if(menu){[['thinking','思考强度','关闭至最高的能力选择'],['location','运行位置','本地环境与连接状态'],['projectMenu','项目菜单','切换项目与打开目录'],['sectionMenu','分组菜单','收起、排序与归档入口'],['screenshot','截图预览','查看完整截图与缩放'],['oauthText','登录输入','文本提示'],['oauthSecret','私密输入','隐藏敏感信息'],['oauthManualCode','授权码输入','从浏览器粘贴验证码'],['oauthSelect','登录选项','选择授权范围']].forEach(([key,title,desc])=>menu.insertAdjacentHTML('beforeend',`<button class="dialog-tile" data-action="dialog-${key}" data-fd-id="card-dialog-${key}"><span class="green">${icon('code',22)}</span><h3>${title}</h3><p class="muted">${desc}</p></button>`));}
 const searchKey=mount.querySelector('.sidebar-search .key');if(searchKey)searchKey.remove();
 const env=mount.querySelector('.composer-top>span');if(env){env.dataset.action='dialog-location';env.style.cursor='pointer';}
 const hint=mount.querySelector('.settings-footer .hint');if(hint)hint.textContent=DEMO.settings==='appearance'?'主题选择后立即生效。':DEMO.settings==='archive'?'永久删除前会再次确认。':DEMO.settings==='about'?'本机数据与版本信息。':'编辑后保存。部分配置将在新会话中生效。';
}
function renderApp(){document.querySelectorAll('[data-owl-mount]').forEach(mount=>{const v=DEMO.view;mount.innerHTML=`<div class="owl-screen" data-fd-id="owl-app-shell">${rail()}${v==='settings'?'':sidebar()}${v==='settings'?settings():`<div class="main">${chrome()}${v==='dialogs'?dialogsGallery():`<div class="body-split ${DEMO.dock==='bottom'?'bottom':''}"><div class="conversation"><div class="chat-scroll">${v==='home'?home():chat()}</div>${composer()}</div>${v==='workspace'?workbench():''}</div>`}</div>`}${modal()}</div>`;enhance(mount);mount.querySelectorAll('[data-fd-editable]').forEach((el,i)=>{if(el.dataset.fdEditable==='true')el.dataset.fdEditable='text';if(!el.dataset.fdId)el.dataset.fdId=`copy-${v}-${DEMO.pane}-${DEMO.settings}-${DEMO.modal||'base'}-${i}`;});});document.querySelectorAll('[data-fd-editable]').forEach(el=>{const key=el.dataset.fdId;if(editedValues.has(key))setEditableValue(el,editedValues.get(key));});if(typeof initDirectEdits==='function')initDirectEdits();restoreComments();renderCatalog();scaleScreens();}
document.addEventListener('input',e=>{const inputEl=e.target.closest('[data-fd-id="field-chat-input"]');if(!inputEl)return;const convo=inputEl.closest('.conversation');convo.querySelector('.slash-suggestions')?.remove();if(!inputEl.value.startsWith('/'))return;convo.insertAdjacentHTML('beforeend',`<div class="slash-suggestions" data-fd-id="section-slash-completion"><div class="tiny" style="margin:0 8px 5px">斜杠命令</div>${[['/model','切换模型','命令'],['/compact','压缩会话上下文','命令'],['/skill:review','审阅代码','技能 · 示例'],['/explain','解释当前代码','模板 · 示例'],['/project-status','查看项目摘要','扩展 · 示例']].filter(([name])=>name.includes(inputEl.value)).map(([name,desc,type])=>`<button class="nav-row" data-action="slash-select" data-command="${name}" style="min-height:32px;font-size:12px"><span class="code" style="color:var(--accent);min-width:130px">${name}</span><span class="muted">${desc}</span><span class="tag" style="margin-left:auto">${type}</span></button>`).join('')}</div>`);});
document.addEventListener('pointerdown',e=>{const handle=e.target.closest('[data-resize-pane]');if(!handle)return;const wb=handle.closest('.workbench');const screen=handle.closest('.owl-screen');const zoom=Number(screen.style.zoom)||1;const startX=e.clientX,startY=e.clientY,width=wb.clientWidth,height=wb.clientHeight;handle.setPointerCapture(e.pointerId);const move=ev=>{if(DEMO.dock==='bottom')wb.style.height=Math.max(180,Math.min(450,height-(ev.clientY-startY)/zoom))+'px';else wb.style.width=Math.max(330,Math.min(670,width-(ev.clientX-startX)/zoom))+'px';};const end=()=>{handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',end);};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',end);e.preventDefault();});
function scaleScreens(){document.querySelectorAll('.canvas-frame').forEach(frame=>{const screen=frame.querySelector('.owl-screen');if(!screen)return;if(document.body.classList.contains('presentation')){screen.style.width=innerWidth+'px';screen.style.height=innerHeight+'px';screen.style.zoom=1;frame.style.height=innerHeight+'px';return;}const scale=frame.clientWidth/1280;screen.style.zoom=scale;frame.style.height=(800*scale)+'px';});}
function renderCatalog(){const cat=document.getElementById('screen-catalog');cat.innerHTML=`<div class="catalog-heading">核心界面</div>${[['home','开始页','chat'],['chat','聊天会话','chat'],['workspace','工作台','panel'],['dialogs','弹窗与状态','shield']].map(([k,t,i])=>`<button data-review-view="${k}" class="${DEMO.view===k?'active':''}">${icon(i,14)}${t}</button>`).join('')}<div class="catalog-heading">工作台 · 9 个面板</div>${paneOrder.map(k=>`<button data-review-pane="${k}" class="${DEMO.view==='workspace'&&DEMO.pane===k?'active':''}">${icon(paneIcons[k],14)}${window.OWL_PANES[k]?.title||k}</button>`).join('')}<div class="catalog-heading">设置 · 8 个分区</div>${settingsOrder.map(k=>`<button data-review-settings="${k}" class="${DEMO.view==='settings'&&DEMO.settings===k?'active':''}">${icon(settingsIcons[k],14)}${window.OWL_SETTINGS[k]?.title||k}</button>`).join('')}`;document.querySelectorAll('[data-review-theme]').forEach(b=>b.classList.toggle('active',b.dataset.reviewTheme===getPaneState()));}
function rememberEdits(){document.querySelectorAll('[data-fd-editable]').forEach(el=>{const key=el.dataset.fdId;if(!key||typeof getEditableValue!=='function')return;const value=getEditableValue(el);editedValues.set(key,value);const initial=directEditInitialValues.get(key);if(initial!==undefined&&initial!==value)recordedEdits.set(key,{selector:directEditSelector(key),label:key,kind:el.dataset.fdEditable||'text',value,initial});else recordedEdits.delete(key);});}
function navigate(view,key){rememberEdits();DEMO.modal=null;DEMO.desktopMenu=null;DEMO.view=view;if(view==='settings'&&key)DEMO.settings=key;if(view==='workspace'&&key)DEMO.pane=key;renderApp();}
document.addEventListener('click',e=>{const review=e.target.closest('[data-review-view],[data-review-pane],[data-review-settings],[data-review-theme]');if(review){if(review.dataset.reviewView)navigate(review.dataset.reviewView);if(review.dataset.reviewPane)navigate('workspace',review.dataset.reviewPane);if(review.dataset.reviewSettings)navigate('settings',review.dataset.reviewSettings);if(review.dataset.reviewTheme){setPaneState(review.dataset.reviewTheme);renderCatalog();setTimeout(scaleScreens,250);}return;}if(typeof commentMode!=='undefined'&&commentMode)return;const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;
 if(a.startsWith('view-')){navigate(a.slice(5));return;}if(a.startsWith('settings-')){navigate('settings',a.slice(9));return;}if(a.startsWith('pane-')){navigate('workspace',a.slice(5));return;}if(a.startsWith('dialog-')){rememberEdits();DEMO.modal=a.slice(7);renderApp();return;}
 if(a==='desktop-menu'){rememberEdits();DEMO.desktopMenu=DEMO.desktopMenu===b.dataset.menu?null:b.dataset.menu;renderApp();return;}
 if(DEMO.desktopMenu)DEMO.desktopMenu=null;
 if(a==='close-modal'){DEMO.modal=null;renderApp();return;}if(a==='toggle-sidebar'){DEMO.sidebar=!DEMO.sidebar;renderApp();return;}if(a==='close-workbench'){navigate('chat');return;}if(a.startsWith('dock-')){DEMO.dock=a.slice(5);DEMO.view='workspace';renderApp();return;}
 if(a==='slash-select'){const input=b.closest('.conversation').querySelector('[data-fd-id="field-chat-input"]');input.value=b.dataset.command+' ';input.dispatchEvent(new Event('change',{bubbles:true}));b.closest('.slash-suggestions').remove();input.focus();return;}
 if(a==='focus-workbench'){DEMO.focus=!DEMO.focus;renderApp();return;}if(a==='split-workbench'){DEMO.split=!DEMO.split;DEMO.focus=DEMO.split||DEMO.focus;renderApp();return;}
 if(a==='toggle-question-nav'){DEMO.questionNav=!DEMO.questionNav;renderApp();return;}if(a==='toggle-shot-preview'){DEMO.shot=!DEMO.shot;renderApp();return;}if(a==='jump-question'){b.closest('.conversation')?.querySelector('.chat-scroll')?.scrollTo({top:0,behavior:'smooth'});return;}
 if(a==='open-modal'){DEMO.modal=b.dataset.value;renderApp();return;}if(a==='manage-models'){navigate('settings','providers');return;}if(a==='open-model-add'){DEMO.modal='modelAdd';renderApp();return;}if(a==='new-chat'){navigate('home');return;}if(a==='choose-project'){DEMO.modal=null;renderApp();showToast('原型：已切换工作目录');return;}
 if(a==='question-cancel'||a==='auth-cancel'){DEMO.modal=null;renderApp();return;}if(a==='oauth-start'||a==='auth-respond'||a==='auth-answer'){DEMO.modal='authSuccess';renderApp();return;}
 if(a==='provider-menu'){DEMO.modal='providerDelete';renderApp();return;}if(a==='provider-delete-confirm'||a==='archive-delete-confirm'||a==='model-delete'){DEMO.modal=null;renderApp();showToast('原型：已删除示例记录');return;}
 if(a==='toggle-plugin'){b.textContent=b.textContent.includes('已启用')?'已停用':'已启用';return;}
 if(a==='toggle'||b.getAttribute('role')==='switch'){b.setAttribute('aria-checked',b.getAttribute('aria-checked')!=='true');return;}
 if(a.startsWith('theme-')){setPaneState(a==='theme-dark'?'dark-expanded':a==='theme-light'?'light-expanded':'split');setTimeout(scaleScreens,250);return;}
 if(a.startsWith('state-')){DEMO.status=a.slice(6);DEMO.running=a==='state-running';if(a==='state-stale'){navigate('workspace','editor');showToast('编辑器外部变更状态已展示');}else navigate(a==='state-empty'?'home':'chat');return;}
 if(a==='provider-add'){DEMO.modal='providerAdd';renderApp();return;}if(a==='model-add'){DEMO.modal='modelAdd';renderApp();return;}if(a==='oauth'){DEMO.modal='oauth';renderApp();return;}
 if(a==='provider-delete'||a==='delete-archive'||a==='file-delete'||a==='discard'||a==='delete-plugin'){DEMO.modal=a==='provider-delete'?'providerDelete':a==='delete-archive'?'archiveDelete':a==='file-delete'?'deleteFile':a==='discard'?'discard':'delete';renderApp();return;}
 if(a==='file-context'){DEMO.modal='fileContext';renderApp();return;}if(a==='file-new'||a==='file-rename'){DEMO.modal=a==='file-new'?'newFolder':'rename';renderApp();return;}if(a==='browser-file-picker'){DEMO.modal='filePicker';renderApp();return;}
 if(a==='question-next'){DEMO.modal='questionFinal';renderApp();return;}if(a==='question-prev'){DEMO.modal='question';renderApp();return;}
 if(a.startsWith('choose-model')){DEMO.model=b.dataset.model||b.dataset.value||b.textContent.trim().split('\n')[0];DEMO.modal=null;renderApp();return;}if(a.startsWith('choose-mode')){DEMO.mode=b.dataset.label||({'confirm':'标准模式','standard':'标准模式','plan':'计划模式','auto':'自动模式'}[b.dataset.value])||b.textContent.trim().split('\n')[0];DEMO.modal=null;renderApp();return;}if(a.startsWith('choose-thinking')){DEMO.thinking=b.dataset.value||b.textContent.trim();DEMO.modal=null;renderApp();return;}
 if(a==='send-demo'){rememberEdits();DEMO.view='chat';DEMO.running=!DEMO.running;renderApp();showToast(DEMO.running?'已展示执行中状态':'已展示停止状态');return;}
 if(a==='editor-stale'){const body=b.closest('.workbench-body');body.insertAdjacentHTML('afterbegin','<div class="notice warning" style="margin:12px">磁盘中的文件已更新。请重新加载或保留当前编辑。 '+button('重新加载','editor-reload','ghost')+'</div>');return;}
 if(a==='editor-reload'){const n=b.closest('.notice');if(n)n.remove();showToast('原型：已重新加载文件');return;}
 if(a==='image-zoom'||a==='image-zoom-in'||a==='image-zoom-out'||a==='image-fit'){const svg=b.closest('.workbench')?.querySelector('[data-fd-id="image-preview-illustration"]');if(svg)svg.style.transform=a==='image-fit'?'none':a==='image-zoom-out'?'scale(.8)':'scale(1.15)';showToast('图片缩放预览');return;}
 if(a==='save'){rememberEdits();const json=document.querySelector('[data-fd-id="settings-field-raw-json"]');if(json){try{JSON.parse(json.value)}catch{showToast('JSON 格式有误，请检查后再保存');return;}}document.querySelectorAll('.settings-save-footer .hint').forEach(el=>el.textContent='已保存 · 原型演示');showToast('原型：已保存。没有写入实际配置。');return;}
 if(['allow','reject','question-submit','project-create','delete-confirm','auth-complete','oauth-complete','provider-save','model-save','archive-confirm','browser-file-submit','file-delete-confirm','discard-confirm','file-new-confirm'].includes(a)){DEMO.modal=a==='oauth-complete'?'authSuccess':null;renderApp();showToast('操作反馈已展示 · 原型数据');return;}
 if(a==='copy-demo'){showToast('原型：已复制');return;}
 if(a==='terminal-clear'){const t=b.closest('.workbench')?.querySelector('.terminal');if(t)t.innerHTML='<span class="green">PS D:\\owl\\owl-mono&gt;</span> <span style="animation:pulse 1s infinite">▍</span>';return;}
 if(a==='terminal-state-toggle'||a==='terminal-restart'){window.OWL_TERMINAL_EXITED=a==='terminal-state-toggle';renderApp();return;}
 if(a==='folder-create'){DEMO.modal=null;renderApp();showToast('原型：已创建文件夹');return;}
 if(a==='task-expand'){const d=b.closest('details');if(d)d.open=!d.open;else showToast('点击执行记录中的箭头查看详情');return;}
 if(a==='select-option'){b.classList.toggle('active');return;}
 showToast('原型：'+(b.textContent.trim()||b.getAttribute('aria-label')||'操作')+' · 已展示交互反馈');
});
window.addEventListener('resize',scaleScreens);
document.addEventListener('click',e=>{if(!DEMO.desktopMenu||e.target.closest('.desktop-titlebar')||commentMode)return;DEMO.desktopMenu=null;renderApp();});
document.querySelectorAll('.pane-toggle-btn').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{scaleScreens();renderCatalog();},250)));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&(DEMO.modal||DEMO.desktopMenu)){DEMO.modal=null;DEMO.desktopMenu=null;renderApp();}});
if(params.has('presentation')){document.body.classList.add('presentation');const theme=params.get('theme')||'dark';document.querySelectorAll('.preview').forEach(p=>p.classList.toggle('hidden-theme',p.dataset.theme!==theme));}
renderApp();
