import { getUiLanguage, useT } from "../i18n/index.ts";

const zh = {
	map: "地图",
	subtitle: "发现值得去的地方",
	mapBadge: "OpenStreetMap 地图",
	newExplore: "新探索",
	favorites: "我的收藏",
	explore: "探索",
	local: "本地",
	localSpace: "本地工作空间",
	localSaved: "地点和探索记录，保存在这里",
	sideSearch: "搜索城市、地址或地点",
	recent: "最近探索",
	historyEmpty: "搜索过的地点会出现在这里",
	clearHistory: "清除探索记录",
	sideTip: "先选择想去的地方，再和 Owl 一起安排这次出发。",
	location: "选择城市或地点",
	locationSearch: "城市、地址或地点",
	locationPlaceholder: "例如：上海、巴黎、台北车站",
	locationSubmit: "搜索地点",
	locationNote: "输入完整名称后搜索，点击结果设置地图中心。",
	coordinatesHint: "也可以输入纬度, 经度，例如 30.25, 120.15。",
	coordinateInvalid: "请输入有效的纬度和经度。纬度范围为 -90 到 90，经度为 -180 到 180。",
	coordinateLocation: "手动位置",
	mapCenter: "地图中心",
	locationCandidates: "选择搜索结果",
	selectedLocation: "当前搜索中心",
	closeLocation: "关闭地点搜索",
	homeTitle: "今天，\n想去哪里？",
	homeDescription: "搜索任意城市、地址或地点，\n再探索附近值得去的地方。",
	homePlaceholder: "和 Owl 聊聊想法，或问问附近有什么…",
	queryLabel: "和 Owl 讨论出行",
	idea: "说说你的想法",
	start: "发送消息",
	exampleLabel: "探索附近",
	sourceNote: "地点资料来自公开地图。营业信息和设施可能未更新，出发前可查看来源核对。",
	categoryAll: "全部地点",
	categoryCafe: "咖啡馆",
	categoryRestaurant: "餐厅",
	categoryPark: "公园",
	categoryMuseum: "博物馆",
	categoryOther: "地点",
	nearby: "探索附近",
	nearbyTitle: "这一带，值得去的地方",
	searchTitle: "找到这些地点",
	savedTitle: "留住喜欢的地方",
	radius: "搜索半径",
	radiusMeters: "{n} 米",
	radiusKm: "{n} 公里",
	nearbySubmit: "搜索附近",
	searching: "正在读取地点…",
	resultsCount: "{n} 个地点",
	savedCount: "{n} 个收藏",
	selectedCenter: "围绕 {name} 搜索",
	searchQuery: "搜索：{query}",
	centerChanged: "地图范围已改变，点击“搜索此区域”更新地点。",
	mapUnavailable: "地点服务暂时不可用，请稍后重试。",
	partialResults: "部分来源暂时不可用，已显示当前可读取的地点。",
	retry: "重试",
	noResults: "没有找到相关地点",
	noResultsHint: "可以尝试更完整的地址，或调整地图中心、类别与半径。",
	noSaved: "还没有收藏的地点",
	noSavedHint: "在地点卡片上点击收藏，就能在这里找到它。",
	sort: "结果排序",
	distanceSort: "按直线距离",
	nameSort: "按名称",
	unknownName: "未命名地点",
	notProvided: "未提供",
	straightDistance: "直线距离",
	distanceMeters: "{n} 米",
	distanceKm: "{n} 公里",
	coordinates: "经纬度",
	source: "数据来源",
	sourceLink: "查看原始地点",
	sourceMap: "OpenStreetMap",
	sourceUser: "你选择的位置",
	fetched: "读取时间",
	address: "地址",
	openingHours: "营业时间",
	phone: "电话",
	website: "网站",
	wheelchair: "无障碍信息",
	internetAccess: "网络信息",
	cuisine: "菜系",
	noExtraInformation: "来源尚未提供更多地点信息。",
	information: "地点信息",
	openWebsite: "打开地点网站",
	sourceDetails: "来源详情",
	viewDetail: "查看 {name} 详情",
	favoritePlace: "收藏 {name}",
	unfavoritePlace: "取消收藏 {name}",
	save: "收藏",
	saved: "已收藏",
	toastFavorite: "已收藏 {name}",
	toastUnfavorite: "已取消收藏 {name}",
	addCompare: "加入比较",
	inCompare: "已加入比较",
	removeCompare: "移出比较",
	askPlace: "问问这家",
	detail: "查看详情",
	detailLabel: "{name} 详情",
	closeDetail: "关闭地点详情",
	detailAsk: "和 Owl 讨论这个地点",
	placePrompt: "结合这个地点已提供的信息，帮我看看这里是否适合这次出行。",
	discussing: "正在讨论：{name}",
	followContext: "继续探索 · {name}",
	followPlaceholder: "补充想法，或讨论地图上的地点…",
	followLabel: "继续讨论地点",
	sendFollowup: "发送追问",
	enterSend: "Enter 发送",
	cancel: "取消",
	comparePlaces: "比较地点",
	startCompare: "开始比较",
	compareNeedTwo: "再加入一个地点，就可以开始比较。",
	compareFull: "最多比较 3 个地点，请先移除一个。",
	compareTitle: "哪个地方，更适合这次出发？",
	compareDimension: "比较项目",
	closeCompare: "关闭比较",
	removeComparePlace: "从比较中移除 {name}",
	compareDiscuss: "让 Owl 帮我比较",
	comparePrompt:
		"请根据这些地点实际提供的位置、类别和设施信息比较它们，说明哪些信息尚未提供，不要编造评分、预算或营业状态。",
	continueBrowse: "继续看看",
	compareNote: "距离为到当前地图中心的直线距离，不代表实际路线或通行时间。",
	mapLabel: "探索地图",
	zoomIn: "放大地图",
	zoomOut: "缩小地图",
	resetMap: "回到搜索中心",
	locate: "使用当前位置",
	locating: "正在获取位置…",
	searchHere: "搜索此区域",
	tilesLoading: "正在加载地图…",
	tilesError: "地图底图暂时无法加载。地点列表仍可使用。",
	locationDenied: "位置权限被拒绝，可以手动搜索城市或地址。",
	locationUnavailable: "暂时无法取得当前位置，可以手动搜索地点。",
	locationTimeout: "获取位置超时，请重试或手动搜索地点。",
	locationInsecure: "当前环境不支持位置权限，请手动搜索城市或地址。",
	searchCenter: "搜索中心",
	conversation: "和 Owl 一起探索",
	conversationEmpty: "可以直接和 Owl 聊聊想法，或继续讨论地图上的地点。",
	conversationYou: "你",
	conversationOwl: "Owl",
	currentModel: "沿用 Owl 当前模型",
	defaultModel: "沿用 Owl 默认模型",
	currentThinking: "思考等级：{level}",
	chatDisconnected: "连接已断开，恢复连接后可以继续发送。",
	chatGenerating: "Owl 正在回复…",
	chatSubmitting: "正在连接这次对话…",
	chatStopped: "已中止本次回复，可以继续提问。",
	chatError: "这次回复未完成",
	chatStop: "中止回复",
	chatStopping: "正在中止…",
	chatThinking: "思考过程",
	chatTool: "正在使用工具",
	chatToolCompleted: "已完成",
	chatToolError: "工具未完成",
	chatToolCancelled: "已取消",
	chatFooter: "和 Owl 继续讨论，当前地图作为参考",
	emptyQuery: "先写下你想讨论的内容。",
	storageUnavailable: "当前环境无法保存探索记录，本次浏览仍可使用。",
} as const;
export type MapCopyKey = keyof typeof zh;
const en: Record<MapCopyKey, string> = {
	map: "Map",
	subtitle: "Discover places worth visiting",
	mapBadge: "OpenStreetMap",
	newExplore: "New exploration",
	favorites: "Saved places",
	explore: "Explore",
	local: "LOCAL",
	localSpace: "Local workspace",
	localSaved: "Your saved places and explorations live here",
	sideSearch: "Search a city, address or place",
	recent: "Recent explorations",
	historyEmpty: "Your place searches will appear here",
	clearHistory: "Clear exploration history",
	sideTip: "Choose where to go, then plan your outing with Owl.",
	location: "Choose a city or place",
	locationSearch: "City, address or place",
	locationPlaceholder: "For example: Shanghai, Paris, Taipei Main Station",
	locationSubmit: "Search places",
	locationNote: "Search a complete name, then choose a result as the map center.",
	coordinatesHint: "You can also enter latitude, longitude, for example 30.25, 120.15.",
	coordinateInvalid: "Enter valid latitude and longitude. Latitude is -90 to 90; longitude is -180 to 180.",
	coordinateLocation: "Manual location",
	mapCenter: "Map center",
	locationCandidates: "Choose a search result",
	selectedLocation: "Current search center",
	closeLocation: "Close place search",
	homeTitle: "Where would you\nlike to go today?",
	homeDescription: "Search any city, address or place,\nthen explore what is nearby.",
	homePlaceholder: "Talk to Owl about your ideas, or ask what is nearby…",
	queryLabel: "Discuss an outing with Owl",
	idea: "Share an idea",
	start: "Send message",
	exampleLabel: "Explore nearby",
	sourceNote:
		"Place information comes from public maps. Hours and facilities may have changed; check the source before visiting.",
	categoryAll: "All places",
	categoryCafe: "Cafes",
	categoryRestaurant: "Restaurants",
	categoryPark: "Parks",
	categoryMuseum: "Museums",
	categoryOther: "Place",
	nearby: "Explore nearby",
	nearbyTitle: "Places worth exploring around here",
	searchTitle: "Places found",
	savedTitle: "Keep your favorite places",
	radius: "Search radius",
	radiusMeters: "{n} m",
	radiusKm: "{n} km",
	nearbySubmit: "Search nearby",
	searching: "Loading places…",
	resultsCount: "{n} places",
	savedCount: "{n} saved places",
	selectedCenter: "Searching around {name}",
	searchQuery: "Search: {query}",
	centerChanged: "The map view changed. Select ‘Search this area’ to update places.",
	mapUnavailable: "The place service is temporarily unavailable. Try again later.",
	partialResults: "Some sources are unavailable. Showing the places currently available.",
	retry: "Retry",
	noResults: "No related places found",
	noResultsHint: "Try a fuller address, or adjust the map center, category and radius.",
	noSaved: "No saved places yet",
	noSavedHint: "Save a place from its card to find it here.",
	sort: "Sort results",
	distanceSort: "Straight-line distance",
	nameSort: "Name",
	unknownName: "Unnamed place",
	notProvided: "Not provided",
	straightDistance: "Straight-line distance",
	distanceMeters: "{n} m",
	distanceKm: "{n} km",
	coordinates: "Coordinates",
	source: "Data source",
	sourceLink: "View original place",
	sourceMap: "OpenStreetMap",
	sourceUser: "Your chosen location",
	fetched: "Retrieved",
	address: "Address",
	openingHours: "Opening hours",
	phone: "Phone",
	website: "Website",
	wheelchair: "Accessibility",
	internetAccess: "Internet access",
	cuisine: "Cuisine",
	noExtraInformation: "The source has not provided more information about this place.",
	information: "Place information",
	openWebsite: "Open the place website",
	sourceDetails: "Source details",
	viewDetail: "View details for {name}",
	favoritePlace: "Save {name}",
	unfavoritePlace: "Unsave {name}",
	save: "Save",
	saved: "Saved",
	toastFavorite: "Saved {name}",
	toastUnfavorite: "Unsaved {name}",
	addCompare: "Compare",
	inCompare: "Added to comparison",
	removeCompare: "Remove from comparison",
	askPlace: "Ask about this place",
	detail: "View details",
	detailLabel: "Details for {name}",
	closeDetail: "Close place details",
	detailAsk: "Discuss this place with Owl",
	placePrompt: "Using the information actually provided for this place, help me decide whether it suits this outing.",
	discussing: "Discussing: {name}",
	followContext: "Keep exploring · {name}",
	followPlaceholder: "Add an idea, or discuss a place on the map…",
	followLabel: "Continue discussing places",
	sendFollowup: "Send follow-up",
	enterSend: "Enter to send",
	cancel: "Cancel",
	comparePlaces: "Compare places",
	startCompare: "Compare",
	compareNeedTwo: "Add one more place to compare.",
	compareFull: "You can compare up to 3 places. Remove one first.",
	compareTitle: "Which place fits this outing?",
	compareDimension: "Criteria",
	closeCompare: "Close comparison",
	removeComparePlace: "Remove {name} from comparison",
	compareDiscuss: "Compare with Owl",
	comparePrompt:
		"Compare these places using the location, category and facilities actually provided. Explain what is missing without inventing ratings, budgets or current opening status.",
	continueBrowse: "Keep browsing",
	compareNote: "Distance is a straight line to the current map center, not a route or travel time.",
	mapLabel: "Explore map",
	zoomIn: "Zoom in",
	zoomOut: "Zoom out",
	resetMap: "Return to search center",
	locate: "Use my location",
	locating: "Getting your location…",
	searchHere: "Search this area",
	tilesLoading: "Loading the map…",
	tilesError: "The map tiles could not load. You can still use the place list.",
	locationDenied: "Location permission was denied. You can search a city or address instead.",
	locationUnavailable: "Your current location is unavailable. You can search a place instead.",
	locationTimeout: "Getting your location timed out. Retry or search a place.",
	locationInsecure: "This environment does not support location permission. Search a city or address instead.",
	searchCenter: "Search center",
	conversation: "Explore with Owl",
	conversationEmpty: "Talk to Owl about your ideas, or discuss a place on the map.",
	conversationYou: "You",
	conversationOwl: "Owl",
	currentModel: "Using Owl's current model",
	defaultModel: "Using Owl's default model",
	currentThinking: "Thinking level: {level}",
	chatDisconnected: "Disconnected. You can send again once the connection recovers.",
	chatGenerating: "Owl is replying…",
	chatSubmitting: "Connecting this conversation…",
	chatStopped: "This reply was stopped. You can keep asking questions.",
	chatError: "This reply did not finish",
	chatStop: "Stop reply",
	chatStopping: "Stopping…",
	chatThinking: "Thinking",
	chatTool: "Using a tool",
	chatToolCompleted: "Completed",
	chatToolError: "Tool did not finish",
	chatToolCancelled: "Cancelled",
	chatFooter: "Continue with Owl using the current map as a reference",
	emptyQuery: "Write something you would like to discuss.",
	storageUnavailable: "This environment cannot save explorations. You can still use this visit.",
};
export function useMapCopy() {
	useT();
	const language = getUiLanguage();
	const dictionary = language === "en" ? en : zh;
	return {
		language,
		text(key: MapCopyKey, vars?: Record<string, string | number>): string {
			return dictionary[key].replace(/\{(\w+)\}/g, (raw, name: string) =>
				vars && name in vars ? String(vars[name]) : raw,
			);
		},
	};
}
